// AUTO-GENERATED by scripts/gen-collision-constants.ts — do not hand-edit.
// Source: packages/game/src/collision/{bodyCapsules,combatSimArena,walkSurfaceReach}.ts
// Re-run from repo root: pnpm content:gen-collision-constants

// --- Body capsules (packages/game/src/collision/bodyCapsules.ts) ---

pub const PLAYER_BODY_RADIUS_M: f32 = 0.22000;
pub const PLAYER_BODY_HEIGHT_STAND_M: f32 = 1.78000;
pub const PLAYER_BODY_HEIGHT_CROUCH_M: f32 = 1.20000;

pub const BABUSHKA_BODY_RADIUS_M: f32 = 0.28000;
pub const BABUSHKA_BODY_HEIGHT_M: f32 = 1.55000;

pub const CAPSULE_PAIR_SURFACE_GAP_M: f32 = 0.10000;

pub const NPC_STATE_DEAD: u8 = 2;

// --- Capsule locomotion tuning (packages/game/src/collision/fpCapsuleLocomotion.ts) ---

pub const COLLISION_EPS: f32 = 0.00150;
pub const STEP_IGNORE_BELOW_FEET_M: f32 = 0.20000;
pub const FP_CHARACTER_MAX_HORIZONTAL_SUBSTEP_M: f32 = 0.18000;
pub const SLIDE_PASSES: usize = 4;
pub const DEPENETRATE_PASSES: usize = 8;
pub const FP_WALK_STEP_UP_MARGIN_M: f32 = 0.82000;
pub const HEAD_CLEARANCE_MIN_CEILING_BOTTOM_ABOVE_FEET_M: f32 = 0.50000;
pub const LOCOMOTION_BLOCKER_QUERY_PAD_M: f32 = 0.35000;
pub const LOCOMOTION_STATIC_MIN_BLOCKER_HEIGHT_M: f32 = 0.04000;

// --- Walk surface reach (packages/game/src/collision/walkSurfaceReach.ts) ---

pub const FP_WALK_FOOT_RADIUS_XZ_M: f32 = 0.22000;
pub const FP_WALK_PROBE_DY_M: f32 = 1.05000;
pub const FP_WALK_MAX_SUPPORT_DROP_BELOW_FEET_M: f32 = 3.10000;

// --- Combat sim arena (packages/game/src/collision/combatSimArena.ts) ---

pub const COMBAT_SIM_FALLBACK_HALF_EXTENT_M: f32 = 14.00000;
pub const COMBAT_SIM_ARENA_PAD_M: f32 = 6.00000;
pub const COMBAT_SIM_WALL_HEIGHT_M: f32 = 4.00000;
pub const COMBAT_SIM_WALL_THICKNESS_M: f32 = 0.35000;
pub const COMBAT_SIM_FLOOR_WALK_INSET_Y_M: f32 = 0.12000;

pub const COMBAT_SIM_TERRAIN_WALK_AABBS_REL: &[([f32; 3], [f32; 3])] = &[
    ([-8.37500, 0.17000, -6.77500], [-6.62500, 0.37500, -5.94500]),
    ([-8.37500, 0.45000, -6.09500], [-6.62500, 0.65500, -5.26500]),
    ([-8.37500, 0.73000, -5.41500], [-6.62500, 0.93500, -4.58500]),
    ([-8.37500, 1.01000, -4.73500], [-6.62500, 1.21500, -3.90500]),
    ([-8.37500, 1.29000, -4.05500], [-6.62500, 1.49500, -3.22500]),
    ([4.77500, 0.19000, 7.57500], [6.22500, 0.39500, 8.37500]),
    ([4.77500, 0.49000, 6.92500], [6.22500, 0.69500, 7.72500]),
    ([4.77500, 0.79000, 6.27500], [6.22500, 0.99500, 7.07500]),
    ([4.77500, 1.09000, 5.62500], [6.22500, 1.29500, 6.42500]),
    ([9.50500, 0.02000, -3.47500], [10.17500, 0.22500, -0.52500]),
    ([8.98500, 0.15000, -3.47500], [9.65500, 0.35500, -0.52500]),
    ([8.46500, 0.28000, -3.47500], [9.13500, 0.48500, -0.52500]),
    ([7.94500, 0.41000, -3.47500], [8.61500, 0.61500, -0.52500]),
    ([7.42500, 0.54000, -3.47500], [8.09500, 0.74500, -0.52500]),
    ([6.90500, 0.67000, -3.47500], [7.57500, 0.87500, -0.52500]),
    ([6.38500, 0.80000, -3.47500], [7.05500, 1.00500, -0.52500]),
    ([5.86500, 0.93000, -3.47500], [6.53500, 1.13500, -0.52500]),
    ([5.34500, 1.06000, -3.47500], [6.01500, 1.26500, -0.52500]),
    ([4.82500, 1.19000, -3.47500], [5.49500, 1.39500, -0.52500]),
    ([-9.07500, 1.29000, -2.27500], [-5.92500, 1.49500, 0.67500]),
    ([6.12500, 1.19000, 1.22500], [8.87500, 1.39500, 3.77500]),
    ([-5.67500, 2.29000, -0.67500], [-4.32500, 2.49500, 0.67500]),
    ([4.42500, 1.89000, -3.57500], [5.57500, 2.09500, -1.42500]),
    ([-1.32500, 2.09000, 5.02500], [1.32500, 2.29500, 5.97500]),
    ([-2.82500, 1.69000, 3.17500], [-1.17500, 1.89500, 4.82500]),
    ([1.92500, 1.39000, -6.52500], [4.07500, 1.59500, -5.47500]),
];

pub const COMBAT_SIM_OBSTACLE_WALK_AABBS_REL: &[([f32; 3], [f32; 3])] = &[
    ([-5.67500, 2.29000, -0.67500], [-4.32500, 2.49500, 0.67500]),
    ([4.42500, 1.89000, -3.57500], [5.57500, 2.09500, -1.42500]),
    ([-1.32500, 2.09000, 5.02500], [1.32500, 2.29500, 5.97500]),
    ([-2.82500, 1.69000, 3.17500], [-1.17500, 1.89500, 4.82500]),
    ([1.92500, 1.39000, -6.52500], [4.07500, 1.59500, -5.47500]),
];

pub const COMBAT_SIM_TERRAIN_COLLISION_AABBS_REL: &[([f32; 3], [f32; 3])] = &[
    ([-8.30000, 0.00000, -6.70000], [-6.70000, 0.28000, -6.02000]),
    ([-8.30000, 0.28000, -6.02000], [-6.70000, 0.56000, -5.34000]),
    ([-8.30000, 0.56000, -5.34000], [-6.70000, 0.84000, -4.66000]),
    ([-8.30000, 0.84000, -4.66000], [-6.70000, 1.12000, -3.98000]),
    ([-8.30000, 1.12000, -3.98000], [-6.70000, 1.40000, -3.30000]),
    ([4.85000, 0.00000, 7.65000], [6.15000, 0.30000, 8.30000]),
    ([4.85000, 0.30000, 7.00000], [6.15000, 0.60000, 7.65000]),
    ([4.85000, 0.60000, 6.35000], [6.15000, 0.90000, 7.00000]),
    ([4.85000, 0.90000, 5.70000], [6.15000, 1.20000, 6.35000]),
    ([9.58000, 0.00000, -3.40000], [10.10000, 0.13000, -0.60000]),
    ([9.06000, 0.13000, -3.40000], [9.58000, 0.26000, -0.60000]),
    ([8.54000, 0.26000, -3.40000], [9.06000, 0.39000, -0.60000]),
    ([8.02000, 0.39000, -3.40000], [8.54000, 0.52000, -0.60000]),
    ([7.50000, 0.52000, -3.40000], [8.02000, 0.65000, -0.60000]),
    ([6.98000, 0.65000, -3.40000], [7.50000, 0.78000, -0.60000]),
    ([6.46000, 0.78000, -3.40000], [6.98000, 0.91000, -0.60000]),
    ([5.94000, 0.91000, -3.40000], [6.46000, 1.04000, -0.60000]),
    ([5.42000, 1.04000, -3.40000], [5.94000, 1.17000, -0.60000]),
    ([4.90000, 1.17000, -3.40000], [5.42000, 1.30000, -0.60000]),
    ([-9.00000, 0.00000, -2.20000], [-6.00000, 1.40000, 0.60000]),
    ([6.20000, 0.00000, 1.30000], [8.80000, 1.30000, 3.70000]),
    ([-3.00000, 0.00000, 8.32500], [3.00000, 1.35000, 8.67500]),
    ([-9.17500, 0.00000, 2.75000], [-8.82500, 1.20000, 7.25000]),
];

pub const COMBAT_SIM_OBSTACLE_COLLISION_AABBS_REL: &[([f32; 3], [f32; 3])] = &[
    ([-5.60000, 0.00000, -0.60000], [-4.40000, 2.40000, 0.60000]),
    ([4.50000, 0.00000, -3.50000], [5.50000, 2.00000, -1.50000]),
    ([-1.25000, 0.00000, 5.10000], [1.25000, 2.20000, 5.90000]),
    ([-2.75000, 0.00000, 3.25000], [-1.25000, 1.80000, 4.75000]),
    ([2.00000, 0.00000, -6.45000], [4.00000, 1.50000, -5.55000]),
];

#[inline]
fn translate_aabb_rel(
    mn: [f32; 3],
    mx: [f32; 3],
    cx: f32,
    foot_y: f32,
    cz: f32,
) -> ([f32; 3], [f32; 3]) {
    (
        [mn[0] + cx, mn[1] + foot_y, mn[2] + cz],
        [mx[0] + cx, mx[1] + foot_y, mx[2] + cz],
    )
}

#[inline]
fn walk_surface_top_is_reachable(
    top: f32,
    feet_y: f32,
    probe_top_y: f32,
    descent_probe: bool,
) -> bool {
    if descent_probe {
        return top <= probe_top_y + 1e-3 && top >= feet_y - FP_WALK_MAX_SUPPORT_DROP_BELOW_FEET_M;
    }
    top <= feet_y + FP_WALK_STEP_UP_MARGIN_M
}

fn sample_walk_top_from_slabs(
    slabs: &[([f32; 3], [f32; 3])],
    x: f32,
    z: f32,
    probe_feet_y: f32,
    probe_top_y: f32,
    descent_probe: bool,
) -> f32 {
    let foot_r = FP_WALK_FOOT_RADIUS_XZ_M;
    let fx0 = x - foot_r;
    let fx1 = x + foot_r;
    let fz0 = z - foot_r;
    let fz1 = z + foot_r;
    let mut best = f32::NAN;
    for (mn, mx) in slabs {
        if fx1 < mn[0] || fx0 > mx[0] || fz1 < mn[2] || fz0 > mx[2] {
            continue;
        }
        let top = mx[1];
        if !walk_surface_top_is_reachable(top, probe_feet_y, probe_top_y, descent_probe) {
            continue;
        }
        best = if best.is_nan() {
            top
        } else {
            best.max(top)
        };
    }
    best
}

fn append_translated_slabs(
    out: &mut Vec<([f32; 3], [f32; 3])>,
    rel: &[([f32; 3], [f32; 3])],
    cx: f32,
    foot_y: f32,
    cz: f32,
) {
    for (mn, mx) in rel {
        out.push(translate_aabb_rel(*mn, *mx, cx, foot_y, cz));
    }
}

fn combat_sim_arena_walk_surface_aabbs_for_unit_bounds(
    bound_min_x: f32,
    bound_max_x: f32,
    bound_min_z: f32,
    bound_max_z: f32,
    foot_y: f32,
) -> Vec<([f32; 3], [f32; 3])> {
    let min_x = bound_min_x - COMBAT_SIM_ARENA_PAD_M;
    let max_x = bound_max_x + COMBAT_SIM_ARENA_PAD_M;
    let min_z = bound_min_z - COMBAT_SIM_ARENA_PAD_M;
    let max_z = bound_max_z + COMBAT_SIM_ARENA_PAD_M;
    let cx = (min_x + max_x) * 0.5;
    let cz = (min_z + max_z) * 0.5;
    let mut out = vec![(
        [min_x, foot_y - COMBAT_SIM_FLOOR_WALK_INSET_Y_M, min_z],
        [max_x, foot_y, max_z],
    )];
    append_translated_slabs(&mut out, COMBAT_SIM_TERRAIN_WALK_AABBS_REL, cx, foot_y, cz);
    append_translated_slabs(&mut out, COMBAT_SIM_OBSTACLE_WALK_AABBS_REL, cx, foot_y, cz);
    out
}

/// Perimeter walls + floor walk + authored cover + terrain — lockstep with TS `combatSimArenaCollisionAabbs`.
pub fn combat_sim_arena_collision_aabbs_for_unit_bounds(
    bound_min_x: f32,
    bound_max_x: f32,
    bound_min_z: f32,
    bound_max_z: f32,
    foot_y: f32,
) -> Vec<([f32; 3], [f32; 3])> {
    let min_x = bound_min_x - COMBAT_SIM_ARENA_PAD_M;
    let max_x = bound_max_x + COMBAT_SIM_ARENA_PAD_M;
    let min_z = bound_min_z - COMBAT_SIM_ARENA_PAD_M;
    let max_z = bound_max_z + COMBAT_SIM_ARENA_PAD_M;
    let wall_y1 = foot_y + COMBAT_SIM_WALL_HEIGHT_M;
    let t = COMBAT_SIM_WALL_THICKNESS_M;
    let cx = (min_x + max_x) * 0.5;
    let cz = (min_z + max_z) * 0.5;
    let mut out = vec![
        (
            [min_x, foot_y - COMBAT_SIM_FLOOR_WALK_INSET_Y_M, min_z],
            [max_x, foot_y, max_z],
        ),
        ([min_x, foot_y, min_z], [min_x + t, wall_y1, max_z]),
        ([max_x - t, foot_y, min_z], [max_x, wall_y1, max_z]),
        ([min_x, foot_y, min_z], [max_x, wall_y1, min_z + t]),
        ([min_x, foot_y, max_z - t], [max_x, wall_y1, max_z]),
    ];
    append_translated_slabs(&mut out, COMBAT_SIM_OBSTACLE_COLLISION_AABBS_REL, cx, foot_y, cz);
    append_translated_slabs(&mut out, COMBAT_SIM_TERRAIN_COLLISION_AABBS_REL, cx, foot_y, cz);
    out
}

/// Highest walk top under probe feet — mirrors client walk spatial index + foot radius.
pub fn combat_sim_sample_walk_top_y_for_unit_bounds(
    bound_min_x: f32,
    bound_max_x: f32,
    bound_min_z: f32,
    bound_max_z: f32,
    foot_y: f32,
    x: f32,
    z: f32,
    probe_feet_y: f32,
) -> f32 {
    let slabs = combat_sim_arena_walk_surface_aabbs_for_unit_bounds(
        bound_min_x,
        bound_max_x,
        bound_min_z,
        bound_max_z,
        foot_y,
    );
    let probe_top_y = probe_feet_y + FP_WALK_PROBE_DY_M;
    let top = sample_walk_top_from_slabs(&slabs, x, z, probe_feet_y, probe_top_y, false);
    if top.is_finite() {
        return top;
    }
    let mut best = foot_y;
    for (mn, mx) in slabs {
        if x < mn[0] || x > mx[0] || z < mn[2] || z > mx[2] {
            continue;
        }
        let slab_top = mx[1];
        if slab_top <= probe_feet_y + FP_WALK_STEP_UP_MARGIN_M + 1e-4
            && slab_top >= probe_feet_y - STEP_IGNORE_BELOW_FEET_M - 1e-4
            && slab_top > best
        {
            best = slab_top;
        }
    }
    best
}
