// AUTO-GENERATED by scripts/gen-walk-aabbs.ts — do not hand-edit.
// Re-run from repo root: pnpm content:gen-walk-aabbs

include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_walk_surfaces/part_0000.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_walk_surfaces/part_0001.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_walk_surfaces/part_0002.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_walk_surfaces/part_0003.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_walk_surfaces/part_0004.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_walk_surfaces/part_0005.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_walk_surfaces/part_0006.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_walk_surfaces/part_0007.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_walk_surfaces/part_0008.rs"));

pub const WALK_SURFACE_FOOTPRINT_MIN_X: f32 = -44.55000;
pub const WALK_SURFACE_FOOTPRINT_MAX_X: f32 = 44.55000;
pub const WALK_SURFACE_FOOTPRINT_MIN_Z: f32 = -147.60000;
pub const WALK_SURFACE_FOOTPRINT_MAX_Z: f32 = 147.60000;

/// Walk AABBs split across `generated_walk_surfaces/part_*.rs` for reviewability.
pub static WALK_SURFACE_AABB_SHARDS: &[&[([f32; 3], [f32; 3])]] = &[
    PART_0000,
    PART_0001,
    PART_0002,
    PART_0003,
    PART_0004,
    PART_0005,
    PART_0006,
    PART_0007,
    PART_0008,
];
