// AUTO-GENERATED by scripts/gen-apartment-door-stock.ts — do not hand-edit.
// Re-run from repo root: pnpm content:gen-apartment-doors

#![allow(dead_code)]

#[derive(Clone, Copy)]
pub struct ApartmentDoorTemplate {
    pub template_id: &'static str,
    pub unit_id: &'static str,
    /// Face code (matches `SwingDoorFace` codes from `@the-mammoth/world`):
    /// 0 = N, 1 = S, 2 = E, 3 = W.
    pub face: u8,
    pub hinge_x: f32,
    pub hinge_z: f32,
    pub feet_y_offset: f32,
    pub panel_w_m: f32,
    pub panel_h_m: f32,
}

#[derive(Clone, Copy)]
pub struct ApartmentDoorTemplateSet {
    pub floor_doc_id: &'static str,
    pub templates: &'static [ApartmentDoorTemplate],
}

static TEMPLATES_0: &[ApartmentDoorTemplate] = &[

];

static TEMPLATES_1: &[ApartmentDoorTemplate] = &[
    ApartmentDoorTemplate { template_id: "manual_e_corridor_near_stair_01|w", unit_id: "manual_e_corridor_near_stair_01", face: 3, hinge_x: 1.92500, hinge_z: -100.84000, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "manual_e_corridor_near_stair_02|w", unit_id: "manual_e_corridor_near_stair_02", face: 3, hinge_x: 1.92500, hinge_z: -54.84000, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "manual_e_corridor_near_stair_03|w", unit_id: "manual_e_corridor_near_stair_03", face: 3, hinge_x: 1.92500, hinge_z: -8.84000, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "manual_e_corridor_near_stair_04|w", unit_id: "manual_e_corridor_near_stair_04", face: 3, hinge_x: 1.92500, hinge_z: 37.16000, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "manual_e_corridor_near_stair_05|w", unit_id: "manual_e_corridor_near_stair_05", face: 3, hinge_x: 1.92500, hinge_z: 83.16000, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_e_001|w", unit_id: "unit_e_001", face: 3, hinge_x: 1.92500, hinge_z: -112.08250, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_e_002|w", unit_id: "unit_e_002", face: 3, hinge_x: 1.92500, hinge_z: -104.88250, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_e_003|w", unit_id: "unit_e_003", face: 3, hinge_x: 1.92500, hinge_z: -75.57000, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_e_004|w", unit_id: "unit_e_004", face: 3, hinge_x: 1.92500, hinge_z: -68.37000, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_e_005|w", unit_id: "unit_e_005", face: 3, hinge_x: 1.92500, hinge_z: -61.17000, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_e_006|w", unit_id: "unit_e_006", face: 3, hinge_x: 1.92500, hinge_z: -29.57000, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_e_007|w", unit_id: "unit_e_007", face: 3, hinge_x: 1.92500, hinge_z: -22.37000, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_e_008|w", unit_id: "unit_e_008", face: 3, hinge_x: 1.92500, hinge_z: -15.17000, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_e_009|w", unit_id: "unit_e_009", face: 3, hinge_x: 1.92500, hinge_z: 16.43000, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_e_010|w", unit_id: "unit_e_010", face: 3, hinge_x: 1.92500, hinge_z: 23.63000, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_e_011|w", unit_id: "unit_e_011", face: 3, hinge_x: 1.92500, hinge_z: 30.83000, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_e_012|w", unit_id: "unit_e_012", face: 3, hinge_x: 1.92500, hinge_z: 62.43000, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_e_013|w", unit_id: "unit_e_013", face: 3, hinge_x: 1.92500, hinge_z: 69.63000, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_e_014|w", unit_id: "unit_e_014", face: 3, hinge_x: 1.92500, hinge_z: 76.83000, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_e_015|w", unit_id: "unit_e_015", face: 3, hinge_x: 1.92500, hinge_z: 106.14250, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_e_016|w", unit_id: "unit_e_016", face: 3, hinge_x: 1.92500, hinge_z: 113.34250, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_w_001|e", unit_id: "unit_w_001", face: 2, hinge_x: -1.92500, hinge_z: -112.08250, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_w_002|e", unit_id: "unit_w_002", face: 2, hinge_x: -1.92500, hinge_z: -104.88250, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_w_003|e", unit_id: "unit_w_003", face: 2, hinge_x: -1.92500, hinge_z: -75.57000, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_w_004|e", unit_id: "unit_w_004", face: 2, hinge_x: -1.92500, hinge_z: -68.37000, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_w_005|e", unit_id: "unit_w_005", face: 2, hinge_x: -1.92500, hinge_z: -61.17000, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_w_006|e", unit_id: "unit_w_006", face: 2, hinge_x: -1.92500, hinge_z: -29.57000, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_w_007|e", unit_id: "unit_w_007", face: 2, hinge_x: -1.92500, hinge_z: -22.37000, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_w_008|e", unit_id: "unit_w_008", face: 2, hinge_x: -1.92500, hinge_z: -15.17000, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_w_009|e", unit_id: "unit_w_009", face: 2, hinge_x: -1.92500, hinge_z: 16.43000, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_w_010|e", unit_id: "unit_w_010", face: 2, hinge_x: -1.92500, hinge_z: 23.63000, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_w_011|e", unit_id: "unit_w_011", face: 2, hinge_x: -1.92500, hinge_z: 30.83000, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_w_012|e", unit_id: "unit_w_012", face: 2, hinge_x: -1.92500, hinge_z: 62.43000, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_w_013|e", unit_id: "unit_w_013", face: 2, hinge_x: -1.92500, hinge_z: 69.63000, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_w_014|e", unit_id: "unit_w_014", face: 2, hinge_x: -1.92500, hinge_z: 76.83000, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_w_015|e", unit_id: "unit_w_015", face: 2, hinge_x: -1.92500, hinge_z: 106.14250, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
    ApartmentDoorTemplate { template_id: "unit_w_016|e", unit_id: "unit_w_016", face: 2, hinge_x: -1.92500, hinge_z: 113.34250, feet_y_offset: 0.23000, panel_w_m: 1.26000, panel_h_m: 2.06000 },
];

pub static APARTMENT_DOOR_TEMPLATE_SETS: &[ApartmentDoorTemplateSet] = &[
    ApartmentDoorTemplateSet { floor_doc_id: "floor_mamutica_ground", templates: TEMPLATES_0 },
    ApartmentDoorTemplateSet { floor_doc_id: "floor_mamutica_typical", templates: TEMPLATES_1 },
];

pub const APARTMENT_DOOR_TEMPLATE_TOTAL: usize = 37;
