// AUTO-GENERATED by scripts/gen-walk-aabbs.ts — do not hand-edit.
// Re-run from repo root: pnpm content:gen-walk-aabbs

include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_collision_solids/part_0000.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_collision_solids/part_0001.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_collision_solids/part_0002.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_collision_solids/part_0003.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_collision_solids/part_0004.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_collision_solids/part_0005.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_collision_solids/part_0006.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_collision_solids/part_0007.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_collision_solids/part_0008.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_collision_solids/part_0009.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_collision_solids/part_0010.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_collision_solids/part_0011.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_collision_solids/part_0012.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_collision_solids/part_0013.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_collision_solids/part_0014.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_collision_solids/part_0015.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_collision_solids/part_0016.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_collision_solids/part_0017.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_collision_solids/part_0018.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_collision_solids/part_0019.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_collision_solids/part_0020.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_collision_solids/part_0021.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_collision_solids/part_0022.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_collision_solids/part_0023.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_collision_solids/part_0024.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_collision_solids/part_0025.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_collision_solids/part_0026.rs"));

#[allow(dead_code)]
pub const COLLISION_SOLID_FOOTPRINT_MIN_X: f32 = -11.72500;
#[allow(dead_code)]
pub const COLLISION_SOLID_FOOTPRINT_MAX_X: f32 = 11.72500;
#[allow(dead_code)]
pub const COLLISION_SOLID_FOOTPRINT_MIN_Z: f32 = -117.06250;
#[allow(dead_code)]
pub const COLLISION_SOLID_FOOTPRINT_MAX_Z: f32 = 117.06250;

/// AABBs split across shard files for reviewability.
pub static COLLISION_SOLID_AABB_SHARDS: &[&[([f32; 3], [f32; 3])]] = &[
    PART_0000,
    PART_0001,
    PART_0002,
    PART_0003,
    PART_0004,
    PART_0005,
    PART_0006,
    PART_0007,
    PART_0008,
    PART_0009,
    PART_0010,
    PART_0011,
    PART_0012,
    PART_0013,
    PART_0014,
    PART_0015,
    PART_0016,
    PART_0017,
    PART_0018,
    PART_0019,
    PART_0020,
    PART_0021,
    PART_0022,
    PART_0023,
    PART_0024,
    PART_0025,
    PART_0026,
];
