// AUTO-GENERATED by scripts/gen-collision-constants.ts — do not hand-edit.
// Source: packages/game/src/collision/{bodyCapsules,combatSimArena,walkSurfaceReach}.ts
// Re-run from repo root: pnpm content:gen-collision-constants

// --- Body capsules (packages/game/src/collision/bodyCapsules.ts) ---

pub const PLAYER_BODY_RADIUS_M: f32 = 0.22000;
pub const PLAYER_BODY_HEIGHT_STAND_M: f32 = 1.78000;
pub const PLAYER_BODY_HEIGHT_CROUCH_M: f32 = 1.20000;

pub const BABUSHKA_BODY_RADIUS_M: f32 = 0.28000;
pub const BABUSHKA_BODY_HEIGHT_M: f32 = 1.55000;

pub const CAPSULE_PAIR_SURFACE_GAP_M: f32 = 0.10000;

pub const NPC_STATE_DEAD: u8 = 2;

// --- Capsule locomotion tuning (packages/game/src/collision/fpCapsuleLocomotion.ts) ---

pub const COLLISION_EPS: f32 = 0.00150;
pub const STEP_IGNORE_BELOW_FEET_M: f32 = 0.20000;
pub const FP_CHARACTER_MAX_HORIZONTAL_SUBSTEP_M: f32 = 0.18000;
pub const SLIDE_PASSES: usize = 4;
pub const DEPENETRATE_PASSES: usize = 8;
pub const FP_WALK_STEP_UP_MARGIN_M: f32 = 0.82000;
pub const HEAD_CLEARANCE_MIN_CEILING_BOTTOM_ABOVE_FEET_M: f32 = 0.50000;
pub const LOCOMOTION_BLOCKER_QUERY_PAD_M: f32 = 0.35000;
pub const LOCOMOTION_STATIC_MIN_BLOCKER_HEIGHT_M: f32 = 0.04000;

// --- Walk surface reach (packages/game/src/collision/walkSurfaceReach.ts) ---

pub const FP_WALK_FOOT_RADIUS_XZ_M: f32 = 0.22000;
pub const FP_WALK_PROBE_DY_M: f32 = 1.05000;
pub const FP_WALK_MAX_SUPPORT_DROP_BELOW_FEET_M: f32 = 3.10000;

// --- Combat sim arena (packages/game/src/collision/combatSimArena.ts) ---

pub const COMBAT_SIM_FALLBACK_HALF_EXTENT_M: f32 = 28.00000;
pub const COMBAT_SIM_ARENA_PAD_M: f32 = 6.00000;
pub const COMBAT_SIM_WALL_HEIGHT_M: f32 = 4.00000;
pub const COMBAT_SIM_WALL_THICKNESS_M: f32 = 0.35000;
pub const COMBAT_SIM_FLOOR_WALK_INSET_Y_M: f32 = 0.12000;

pub const COMBAT_SIM_TERRAIN_WALK_AABBS_REL: &[([f32; 3], [f32; 3])] = &[
    ([-21.17500, 0.17000, -21.07500], [-18.82500, 0.37500, -20.06786]),
    ([-21.17500, 0.45000, -20.21786], [-18.82500, 0.65500, -19.21071]),
    ([-21.17500, 0.73000, -19.36071], [-18.82500, 0.93500, -18.35357]),
    ([-21.17500, 1.01000, -18.50357], [-18.82500, 1.21500, -17.49643]),
    ([-21.17500, 1.29000, -17.64643], [-18.82500, 1.49500, -16.63929]),
    ([-21.17500, 1.57000, -16.78929], [-18.82500, 1.77500, -15.78214]),
    ([-21.17500, 1.85000, -15.93214], [-18.82500, 2.05500, -14.92500]),
    ([16.92500, 0.17000, 19.75833], [19.07500, 0.37500, 20.82500]),
    ([16.92500, 0.45000, 18.84167], [19.07500, 0.65500, 19.90833]),
    ([16.92500, 0.73000, 17.92500], [19.07500, 0.93500, 18.99167]),
    ([16.92500, 1.01000, 17.00833], [19.07500, 1.21500, 18.07500]),
    ([16.92500, 1.29000, 16.09167], [19.07500, 1.49500, 17.15833]),
    ([16.92500, 1.57000, 15.17500], [19.07500, 1.77500, 16.24167]),
    ([24.09167, 0.01500, -14.07500], [25.07500, 0.22000, -9.92500]),
    ([23.25833, 0.14000, -14.07500], [24.24167, 0.34500, -9.92500]),
    ([22.42500, 0.26500, -14.07500], [23.40833, 0.47000, -9.92500]),
    ([21.59167, 0.39000, -14.07500], [22.57500, 0.59500, -9.92500]),
    ([20.75833, 0.51500, -14.07500], [21.74167, 0.72000, -9.92500]),
    ([19.92500, 0.64000, -14.07500], [20.90833, 0.84500, -9.92500]),
    ([19.09167, 0.76500, -14.07500], [20.07500, 0.97000, -9.92500]),
    ([18.25833, 0.89000, -14.07500], [19.24167, 1.09500, -9.92500]),
    ([17.42500, 1.01500, -14.07500], [18.40833, 1.22000, -9.92500]),
    ([16.59167, 1.14000, -14.07500], [17.57500, 1.34500, -9.92500]),
    ([15.75833, 1.26500, -14.07500], [16.74167, 1.47000, -9.92500]),
    ([14.92500, 1.39000, -14.07500], [15.90833, 1.59500, -9.92500]),
    ([-24.57500, 0.01500, 12.17500], [-23.52500, 0.22000, 15.82500]),
    ([-23.67500, 0.14000, 12.17500], [-22.62500, 0.34500, 15.82500]),
    ([-22.77500, 0.26500, 12.17500], [-21.72500, 0.47000, 15.82500]),
    ([-21.87500, 0.39000, 12.17500], [-20.82500, 0.59500, 15.82500]),
    ([-20.97500, 0.51500, 12.17500], [-19.92500, 0.72000, 15.82500]),
    ([-20.07500, 0.64000, 12.17500], [-19.02500, 0.84500, 15.82500]),
    ([-19.17500, 0.76500, 12.17500], [-18.12500, 0.97000, 15.82500]),
    ([-18.27500, 0.89000, 12.17500], [-17.22500, 1.09500, 15.82500]),
    ([-17.37500, 1.01500, 12.17500], [-16.32500, 1.22000, 15.82500]),
    ([-16.47500, 1.14000, 12.17500], [-15.42500, 1.34500, 15.82500]),
    ([-22.07500, 1.85000, -14.87500], [-17.92500, 2.05500, -10.72500]),
    ([15.92500, 1.57000, 10.97500], [20.07500, 1.77500, 15.12500]),
    ([11.72500, 1.39000, -13.82500], [14.87500, 1.59500, -10.17500]),
    ([-14.87500, 1.14000, 12.42500], [-10.22500, 1.34500, 15.57500]),
    ([-10.77500, 2.29000, -6.77500], [-9.22500, 2.49500, -5.22500]),
    ([11.32500, 1.89000, -15.17500], [12.67500, 2.09500, -12.82500]),
    ([4.52500, 2.09000, 9.42500], [7.47500, 2.29500, 10.57500]),
    ([-14.97500, 1.69000, 11.02500], [-13.02500, 1.89500, 12.97500]),
    ([12.92500, 1.39000, 5.37500], [15.07500, 1.59500, 6.62500]),
    ([-1.27500, 1.49000, -22.67500], [1.27500, 1.69500, -21.32500]),
];

pub const COMBAT_SIM_OBSTACLE_WALK_AABBS_REL: &[([f32; 3], [f32; 3])] = &[
    ([-10.77500, 2.29000, -6.77500], [-9.22500, 2.49500, -5.22500]),
    ([11.32500, 1.89000, -15.17500], [12.67500, 2.09500, -12.82500]),
    ([4.52500, 2.09000, 9.42500], [7.47500, 2.29500, 10.57500]),
    ([-14.97500, 1.69000, 11.02500], [-13.02500, 1.89500, 12.97500]),
    ([12.92500, 1.39000, 5.37500], [15.07500, 1.59500, 6.62500]),
    ([-1.27500, 1.49000, -22.67500], [1.27500, 1.69500, -21.32500]),
];

pub const COMBAT_SIM_TERRAIN_COLLISION_AABBS_REL: &[([f32; 3], [f32; 3])] = &[
    ([-21.10000, 0.00000, -21.00000], [-18.90000, 0.28000, -20.14286]),
    ([-21.10000, 0.28000, -20.14286], [-18.90000, 0.56000, -19.28571]),
    ([-21.10000, 0.56000, -19.28571], [-18.90000, 0.84000, -18.42857]),
    ([-21.10000, 0.84000, -18.42857], [-18.90000, 1.12000, -17.57143]),
    ([-21.10000, 1.12000, -17.57143], [-18.90000, 1.40000, -16.71429]),
    ([-21.10000, 1.40000, -16.71429], [-18.90000, 1.68000, -15.85714]),
    ([-21.10000, 1.68000, -15.85714], [-18.90000, 1.96000, -15.00000]),
    ([17.00000, 0.00000, 19.83333], [19.00000, 0.28000, 20.75000]),
    ([17.00000, 0.28000, 18.91667], [19.00000, 0.56000, 19.83333]),
    ([17.00000, 0.56000, 18.00000], [19.00000, 0.84000, 18.91667]),
    ([17.00000, 0.84000, 17.08333], [19.00000, 1.12000, 18.00000]),
    ([17.00000, 1.12000, 16.16667], [19.00000, 1.40000, 17.08333]),
    ([17.00000, 1.40000, 15.25000], [19.00000, 1.68000, 16.16667]),
    ([24.16667, 0.00000, -14.00000], [25.00000, 0.12500, -10.00000]),
    ([23.33333, 0.12500, -14.00000], [24.16667, 0.25000, -10.00000]),
    ([22.50000, 0.25000, -14.00000], [23.33333, 0.37500, -10.00000]),
    ([21.66667, 0.37500, -14.00000], [22.50000, 0.50000, -10.00000]),
    ([20.83333, 0.50000, -14.00000], [21.66667, 0.62500, -10.00000]),
    ([20.00000, 0.62500, -14.00000], [20.83333, 0.75000, -10.00000]),
    ([19.16667, 0.75000, -14.00000], [20.00000, 0.87500, -10.00000]),
    ([18.33333, 0.87500, -14.00000], [19.16667, 1.00000, -10.00000]),
    ([17.50000, 1.00000, -14.00000], [18.33333, 1.12500, -10.00000]),
    ([16.66667, 1.12500, -14.00000], [17.50000, 1.25000, -10.00000]),
    ([15.83333, 1.25000, -14.00000], [16.66667, 1.37500, -10.00000]),
    ([15.00000, 1.37500, -14.00000], [15.83333, 1.50000, -10.00000]),
    ([-24.50000, 0.00000, 12.25000], [-23.60000, 0.12500, 15.75000]),
    ([-23.60000, 0.12500, 12.25000], [-22.70000, 0.25000, 15.75000]),
    ([-22.70000, 0.25000, 12.25000], [-21.80000, 0.37500, 15.75000]),
    ([-21.80000, 0.37500, 12.25000], [-20.90000, 0.50000, 15.75000]),
    ([-20.90000, 0.50000, 12.25000], [-20.00000, 0.62500, 15.75000]),
    ([-20.00000, 0.62500, 12.25000], [-19.10000, 0.75000, 15.75000]),
    ([-19.10000, 0.75000, 12.25000], [-18.20000, 0.87500, 15.75000]),
    ([-18.20000, 0.87500, 12.25000], [-17.30000, 1.00000, 15.75000]),
    ([-17.30000, 1.00000, 12.25000], [-16.40000, 1.12500, 15.75000]),
    ([-16.40000, 1.12500, 12.25000], [-15.50000, 1.25000, 15.75000]),
    ([-22.00000, 1.74000, -14.80000], [-18.00000, 1.96000, -10.80000]),
    ([16.00000, 1.46000, 11.05000], [20.00000, 1.68000, 15.05000]),
    ([11.80000, 1.28000, -13.75000], [14.80000, 1.50000, -10.25000]),
    ([-14.80000, 1.03000, 12.50000], [-10.30000, 1.25000, 15.50000]),
    ([-5.00000, 0.00000, -0.17500], [5.00000, 1.25000, 0.17500]),
    ([-14.17500, 0.00000, 4.50000], [-13.82500, 1.35000, 11.50000]),
    ([7.75494, 0.00000, 11.75494], [12.24506, 1.20000, 16.24506]),
];

pub const COMBAT_SIM_OBSTACLE_COLLISION_AABBS_REL: &[([f32; 3], [f32; 3])] = &[
    ([-10.70000, 0.00000, -6.70000], [-9.30000, 2.40000, -5.30000]),
    ([11.40000, 0.00000, -15.10000], [12.60000, 2.00000, -12.90000]),
    ([4.60000, 0.00000, 9.50000], [7.40000, 2.20000, 10.50000]),
    ([-14.90000, 0.00000, 11.10000], [-13.10000, 1.80000, 12.90000]),
    ([13.00000, 0.00000, 5.45000], [15.00000, 1.50000, 6.55000]),
    ([-1.20000, 0.00000, -22.60000], [1.20000, 1.60000, -21.40000]),
];

#[inline]
fn translate_aabb_rel(
    mn: [f32; 3],
    mx: [f32; 3],
    cx: f32,
    foot_y: f32,
    cz: f32,
) -> ([f32; 3], [f32; 3]) {
    (
        [mn[0] + cx, mn[1] + foot_y, mn[2] + cz],
        [mx[0] + cx, mx[1] + foot_y, mx[2] + cz],
    )
}

#[inline]
fn walk_surface_top_is_reachable(
    top: f32,
    feet_y: f32,
    probe_top_y: f32,
    descent_probe: bool,
) -> bool {
    if descent_probe {
        return top <= probe_top_y + 1e-3 && top >= feet_y - FP_WALK_MAX_SUPPORT_DROP_BELOW_FEET_M;
    }
    top <= feet_y + FP_WALK_STEP_UP_MARGIN_M
}

fn sample_walk_top_from_slabs(
    slabs: &[([f32; 3], [f32; 3])],
    x: f32,
    z: f32,
    probe_feet_y: f32,
    probe_top_y: f32,
    descent_probe: bool,
) -> f32 {
    let foot_r = FP_WALK_FOOT_RADIUS_XZ_M;
    let fx0 = x - foot_r;
    let fx1 = x + foot_r;
    let fz0 = z - foot_r;
    let fz1 = z + foot_r;
    let mut best = f32::NAN;
    for (mn, mx) in slabs {
        if fx1 < mn[0] || fx0 > mx[0] || fz1 < mn[2] || fz0 > mx[2] {
            continue;
        }
        let top = mx[1];
        if !walk_surface_top_is_reachable(top, probe_feet_y, probe_top_y, descent_probe) {
            continue;
        }
        best = if best.is_nan() {
            top
        } else {
            best.max(top)
        };
    }
    best
}

fn append_translated_slabs(
    out: &mut Vec<([f32; 3], [f32; 3])>,
    rel: &[([f32; 3], [f32; 3])],
    cx: f32,
    foot_y: f32,
    cz: f32,
) {
    for (mn, mx) in rel {
        out.push(translate_aabb_rel(*mn, *mx, cx, foot_y, cz));
    }
}

fn combat_sim_arena_walk_surface_aabbs_for_unit_bounds(
    bound_min_x: f32,
    bound_max_x: f32,
    bound_min_z: f32,
    bound_max_z: f32,
    foot_y: f32,
) -> Vec<([f32; 3], [f32; 3])> {
    let min_x = bound_min_x - COMBAT_SIM_ARENA_PAD_M;
    let max_x = bound_max_x + COMBAT_SIM_ARENA_PAD_M;
    let min_z = bound_min_z - COMBAT_SIM_ARENA_PAD_M;
    let max_z = bound_max_z + COMBAT_SIM_ARENA_PAD_M;
    let cx = (min_x + max_x) * 0.5;
    let cz = (min_z + max_z) * 0.5;
    let mut out = vec![(
        [min_x, foot_y - COMBAT_SIM_FLOOR_WALK_INSET_Y_M, min_z],
        [max_x, foot_y, max_z],
    )];
    append_translated_slabs(&mut out, COMBAT_SIM_TERRAIN_WALK_AABBS_REL, cx, foot_y, cz);
    append_translated_slabs(&mut out, COMBAT_SIM_OBSTACLE_WALK_AABBS_REL, cx, foot_y, cz);
    out
}

/// Perimeter walls + floor walk + authored cover + terrain — lockstep with TS `combatSimArenaCollisionAabbs`.
pub fn combat_sim_arena_collision_aabbs_for_unit_bounds(
    bound_min_x: f32,
    bound_max_x: f32,
    bound_min_z: f32,
    bound_max_z: f32,
    foot_y: f32,
) -> Vec<([f32; 3], [f32; 3])> {
    let min_x = bound_min_x - COMBAT_SIM_ARENA_PAD_M;
    let max_x = bound_max_x + COMBAT_SIM_ARENA_PAD_M;
    let min_z = bound_min_z - COMBAT_SIM_ARENA_PAD_M;
    let max_z = bound_max_z + COMBAT_SIM_ARENA_PAD_M;
    let wall_y1 = foot_y + COMBAT_SIM_WALL_HEIGHT_M;
    let t = COMBAT_SIM_WALL_THICKNESS_M;
    let cx = (min_x + max_x) * 0.5;
    let cz = (min_z + max_z) * 0.5;
    let mut out = vec![
        (
            [min_x, foot_y - COMBAT_SIM_FLOOR_WALK_INSET_Y_M, min_z],
            [max_x, foot_y, max_z],
        ),
        ([min_x, foot_y, min_z], [min_x + t, wall_y1, max_z]),
        ([max_x - t, foot_y, min_z], [max_x, wall_y1, max_z]),
        ([min_x, foot_y, min_z], [max_x, wall_y1, min_z + t]),
        ([min_x, foot_y, max_z - t], [max_x, wall_y1, max_z]),
    ];
    append_translated_slabs(&mut out, COMBAT_SIM_OBSTACLE_COLLISION_AABBS_REL, cx, foot_y, cz);
    append_translated_slabs(&mut out, COMBAT_SIM_TERRAIN_COLLISION_AABBS_REL, cx, foot_y, cz);
    out
}

/// Highest walk top under probe feet — mirrors client walk spatial index + foot radius.
pub fn combat_sim_sample_walk_top_y_for_unit_bounds(
    bound_min_x: f32,
    bound_max_x: f32,
    bound_min_z: f32,
    bound_max_z: f32,
    foot_y: f32,
    x: f32,
    z: f32,
    probe_feet_y: f32,
) -> f32 {
    let slabs = combat_sim_arena_walk_surface_aabbs_for_unit_bounds(
        bound_min_x,
        bound_max_x,
        bound_min_z,
        bound_max_z,
        foot_y,
    );
    let probe_top_y = probe_feet_y + FP_WALK_PROBE_DY_M;
    let top = sample_walk_top_from_slabs(&slabs, x, z, probe_feet_y, probe_top_y, false);
    if top.is_finite() {
        return top;
    }
    let mut best = foot_y;
    for (mn, mx) in slabs {
        if x < mn[0] || x > mx[0] || z < mn[2] || z > mx[2] {
            continue;
        }
        let slab_top = mx[1];
        if slab_top <= probe_feet_y + FP_WALK_STEP_UP_MARGIN_M + 1e-4
            && slab_top >= probe_feet_y - STEP_IGNORE_BELOW_FEET_M - 1e-4
            && slab_top > best
        {
            best = slab_top;
        }
    }
    best
}
