// AUTO-GENERATED by scripts/gen-walk-aabbs.ts — do not hand-edit.
// Re-run from repo root: pnpm content:gen-walk-aabbs

include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_walk_surfaces/part_0000.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_walk_surfaces/part_0001.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_walk_surfaces/part_0002.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_walk_surfaces/part_0003.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_walk_surfaces/part_0004.rs"));

#[allow(dead_code)]
pub const WALK_SURFACE_FOOTPRINT_MIN_X: f32 = -16.55000;
#[allow(dead_code)]
pub const WALK_SURFACE_FOOTPRINT_MAX_X: f32 = 16.55000;
#[allow(dead_code)]
pub const WALK_SURFACE_FOOTPRINT_MIN_Z: f32 = -119.60000;
#[allow(dead_code)]
pub const WALK_SURFACE_FOOTPRINT_MAX_Z: f32 = 119.60000;

/// AABBs split across shard files for reviewability.
pub static WALK_SURFACE_AABB_SHARDS: &[&[([f32; 3], [f32; 3])]] = &[
    PART_0000,
    PART_0001,
    PART_0002,
    PART_0003,
    PART_0004,
];
