// AUTO-GENERATED by scripts/gen-walk-aabbs.ts — do not hand-edit.
// Re-run from repo root: pnpm content:gen-walk-aabbs

include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_unit_window_walk_surfaces/part_0000.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_unit_window_walk_surfaces/part_0001.rs"));
include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_unit_window_walk_surfaces/part_0002.rs"));

#[allow(dead_code)]
pub const UNIT_WINDOW_WALK_SURFACE_FOOTPRINT_MIN_X: f32 = -12.06500;
#[allow(dead_code)]
pub const UNIT_WINDOW_WALK_SURFACE_FOOTPRINT_MAX_X: f32 = 12.06500;
#[allow(dead_code)]
pub const UNIT_WINDOW_WALK_SURFACE_FOOTPRINT_MIN_Z: f32 = -115.96250;
#[allow(dead_code)]
pub const UNIT_WINDOW_WALK_SURFACE_FOOTPRINT_MAX_Z: f32 = 115.96250;

/// AABBs split across shard files for reviewability.
pub static UNIT_WINDOW_WALK_SURFACE_AABB_SHARDS: &[&[([f32; 3], [f32; 3])]] = &[
    PART_0000,
    PART_0001,
    PART_0002,
];
