export {
  COMBAT_SIM_ARENA_PAD_M,
  COMBAT_SIM_AUTHORED_OBSTACLES,
  COMBAT_SIM_DECK_SLAB_THICK_M,
  COMBAT_SIM_DECKS,
  COMBAT_SIM_FALLBACK_HALF_EXTENT_M,
  COMBAT_SIM_LOW_WALLS,
  COMBAT_SIM_RAMPS,
  COMBAT_SIM_STEP_STACKS,
  COMBAT_SIM_WALL_HEIGHT_M,
  COMBAT_SIM_WALL_THICKNESS_M,
  COMBAT_SIM_WALK_SEAM_PAD_XZ_M,
  COMBAT_SIM_WALK_SEAM_PAD_Y_HI_M,
  COMBAT_SIM_WALK_TREAD_THICK_M,
  combatSimArenaBoundsFromUnitFootprint,
  combatSimSessionArenaBounds,
  combatSimSessionPlayFootprint,
  combatSimArenaCollisionAabbs,
  combatSimArenaDeckSlabAabbs,
  combatSimArenaLowWallAabbs,
  combatSimArenaObstacleAabbs,
  combatSimArenaObstacleWalkAabbs,
  combatSimArenaPerimeterWallAabbs,
  combatSimArenaRampCollisionAabbs,
  combatSimArenaStepCollisionAabbs,
  combatSimArenaTerrainCollisionAabbs,
  combatSimArenaWalkSurfaceAabbs,
  combatSimSampleWalkTopY,
  type CollisionAabbLike,
  type CombatSimArenaBounds,
  type CombatSimDeckSpec,
  type CombatSimLowWallSpec,
  type CombatSimObstacleSpec,
  type CombatSimRampSpec,
  type CombatSimStepStackSpec,
} from "./combatSimArena.js";
export {
  BABUSHKA_BODY_HEIGHT_M,
  BABUSHKA_BODY_RADIUS_M,
  CAPSULE_PAIR_SURFACE_GAP_M,
  NPC_STATE_DEAD,
  PLAYER_BODY_HEIGHT_CROUCH_M,
  PLAYER_BODY_HEIGHT_STAND_M,
  PLAYER_BODY_RADIUS_M,
  babushkaMinPeerCenterDistanceM,
  babushkaMinPlayerCenterDistanceM,
  capsuleMinCenterDistanceM,
  isLivingWorldNpc,
  npcBodyDimsForArchetype,
  npcCapsuleCollisionAabb,
  playerBodyHeightM,
  verticalCapsuleOverlap,
  type NpcArchetypeBodyDims,
} from "./bodyCapsules.js";
export {
  COLLISION_EPS,
  DEPENETRATE_PASSES,
  FP_CHARACTER_MAX_HORIZONTAL_SUBSTEP_M,
  FP_WALK_STEP_UP_MARGIN_M,
  HEAD_CLEARANCE_MIN_CEILING_BOTTOM_ABOVE_FEET_M,
  LOCOMOTION_BLOCKER_QUERY_PAD_M,
  LOCOMOTION_STATIC_MIN_BLOCKER_HEIGHT_M,
  SLIDE_PASSES,
  STEP_IGNORE_BELOW_FEET_M,
} from "./fpCapsuleLocomotion.js";
export {
  LOCOMOTION_DYNAMIC_BLOCKER_SOURCE_ORDER,
  locomotionBlockerQueryDisjointAabb,
  locomotionBlockerQueryFromCapsuleMove,
  locomotionStaticBlockerHeightOk,
  locomotionVerticalOverlapFeetBody,
  visitLocomotionDynamicBlockersInOrder,
  type LocomotionBlockerQuery,
  type LocomotionDynamicBlockerSource,
  type LocomotionDynamicBlockerSources,
  type LocomotionDynamicBlockerVisitor,
} from "./locomotionBlockers.js";
export {
  FP_WALK_FOOT_RADIUS_XZ_M,
  FP_WALK_MAX_SUPPORT_DROP_BELOW_FEET_M,
  FP_WALK_PROBE_DY_M,
  sampleGroundedWalkTopFromSlabs,
  sampleWalkTopFromSlabs,
  walkSurfaceTopIsReachable,
  type SampleWalkTopFromSlabsOpts,
  type WalkSurfaceReachOpts,
} from "./walkSurfaceReach.js";
export {
  partitionWallLocalSlabAabbs,
  partitionWallWorldCollisionAabbs,
  type PartitionWallWorldPose,
} from "./partitionWallCollision.js";
