// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  unitKey: __t.string().primaryKey().name("unit_key"),
  powerOn: __t.u8().name("power_on"),
  powerRestoreAfterMinutes: __t.u16().name("power_restore_after_minutes"),
  waterTankOk: __t.u8().name("water_tank_ok"),
  waterRestoreAfterMinutes: __t.u16().name("water_restore_after_minutes"),
});
