// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  unitKey: __t.string().primaryKey().name("unit_key"),
  floorDocId: __t.string().name("floor_doc_id"),
  level: __t.u32(),
  unitId: __t.string().name("unit_id"),
  state: __t.u8(),
  owner: __t.option(__t.identity()),
  claimProgressSecs: __t.f32().name("claim_progress_secs"),
  claimStartedBy: __t.option(__t.identity()).name("claim_started_by"),
  lastClaimPulseMicros: __t.i64().name("last_claim_pulse_micros"),
  reinforceProgressSecs: __t.f32().name("reinforce_progress_secs"),
  reinforceBy: __t.option(__t.identity()).name("reinforce_by"),
  reinforced: __t.u8(),
  bedX: __t.f32().name("bed_x"),
  bedY: __t.f32().name("bed_y"),
  bedZ: __t.f32().name("bed_z"),
  bedYaw: __t.f32().name("bed_yaw"),
  footX: __t.f32().name("foot_x"),
  footY: __t.f32().name("foot_y"),
  footZ: __t.f32().name("foot_z"),
  wardrobeX: __t.f32().name("wardrobe_x"),
  wardrobeZ: __t.f32().name("wardrobe_z"),
  boundMinX: __t.f32().name("bound_min_x"),
  boundMaxX: __t.f32().name("bound_max_x"),
  boundMinZ: __t.f32().name("bound_min_z"),
  boundMaxZ: __t.f32().name("bound_max_z"),
  boundMinY: __t.f32().name("bound_min_y"),
  boundMaxY: __t.f32().name("bound_max_y"),
});
