// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  blockerId: __t.u64().primaryKey().name("blocker_id"),
  unitKey: __t.string().name("unit_key"),
  minX: __t.f32().name("min_x"),
  minY: __t.f32().name("min_y"),
  minZ: __t.f32().name("min_z"),
  maxX: __t.f32().name("max_x"),
  maxY: __t.f32().name("max_y"),
  maxZ: __t.f32().name("max_z"),
});
