// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  rowKey: __t.string().primaryKey().name("row_key"),
  floorDocId: __t.string().name("floor_doc_id"),
  level: __t.u32(),
  templateId: __t.string().name("template_id"),
  face: __t.u8(),
  hingeX: __t.f32().name("hinge_x"),
  hingeZ: __t.f32().name("hinge_z"),
  feetY: __t.f32().name("feet_y"),
  panelWM: __t.f32().name("panel_w_m"),
  panelHM: __t.f32().name("panel_h_m"),
  desiredOpen: __t.u8().name("desired_open"),
  swingOpen01: __t.f32().name("swing_open_01"),
});
