// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  shaftKey: __t.string().primaryKey().name("shaft_key"),
  currentLevel: __t.u32().name("current_level"),
  doorOpen01: __t.f32().name("door_open_01"),
  phase: __t.u8(),
  moveFromLevel: __t.u32().name("move_from_level"),
  moveToLevel: __t.u32().name("move_to_level"),
  moveU: __t.f32().name("move_u"),
  destQueue: __t.array(__t.u32()).name("dest_queue"),
  cabFloorY: __t.f32().name("cab_floor_y"),
  doorFace: __t.u8().name("door_face"),
  plateX: __t.f32().name("plate_x"),
  plateZ: __t.f32().name("plate_z"),
});
