// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  rowKey: __t.string().primaryKey().name("row_key"),
  shaftKey: __t.string().name("shaft_key"),
  level: __t.u32(),
  desiredOpen: __t.u8().name("desired_open"),
  swingOpen01: __t.f32().name("swing_open_01"),
});
