// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.1 (commit a4d29daec8ed35ce4913a335b7210b9ae3933d00).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddApartmentUnitDecorReducer from "./add_apartment_unit_decor_reducer";
import AddCombatSimNpcSpawnReducer from "./add_combat_sim_npc_spawn_reducer";
import ApartmentDoorSetReducer from "./apartment_door_set_reducer";
import ApartmentDoorToggleReducer from "./apartment_door_toggle_reducer";
import CancelWaitingCraftReducer from "./cancel_waiting_craft_reducer";
import ClaimApartmentPulseReducer from "./claim_apartment_pulse_reducer";
import ClearCombatSimNpcSpawnsReducer from "./clear_combat_sim_npc_spawns_reducer";
import ConsumeHotbarItemReducer from "./consume_hotbar_item_reducer";
import DeleteApartmentUnitDecorReducer from "./delete_apartment_unit_decor_reducer";
import DropItemReducer from "./drop_item_reducer";
import DumpWaterFromBottleReducer from "./dump_water_from_bottle_reducer";
import ElevatorHailReducer from "./elevator_hail_reducer";
import ElevatorLandingExteriorDoorSetReducer from "./elevator_landing_exterior_door_set_reducer";
import ElevatorLandingExteriorDoorToggleReducer from "./elevator_landing_exterior_door_toggle_reducer";
import ElevatorSelectFloorReducer from "./elevator_select_floor_reducer";
import EnqueueCraftReducer from "./enqueue_craft_reducer";
import EnterCombatSimReducer from "./enter_combat_sim_reducer";
import FillWaterBottleAtTankReducer from "./fill_water_bottle_at_tank_reducer";
import HarvestBalconyGrowSlotReducer from "./harvest_balcony_grow_slot_reducer";
import LeaveCombatSimReducer from "./leave_combat_sim_reducer";
import MoveItemToHotbarReducer from "./move_item_to_hotbar_reducer";
import MoveItemToInventoryReducer from "./move_item_to_inventory_reducer";
import PickupDroppedItemReducer from "./pickup_dropped_item_reducer";
import PingWorldReducer from "./ping_world_reducer";
import PlantBalconyGrowSlotReducer from "./plant_balcony_grow_slot_reducer";
import ReinforceApartmentPulseReducer from "./reinforce_apartment_pulse_reducer";
import RespawnPlayerReducer from "./respawn_player_reducer";
import SetActiveHotbarSlotReducer from "./set_active_hotbar_slot_reducer";
import SetAvatarBodyReducer from "./set_avatar_body_reducer";
import SetOwnedApartmentPiecePoseReducer from "./set_owned_apartment_piece_pose_reducer";
import SetUsernameReducer from "./set_username_reducer";
import SleepInBedReducer from "./sleep_in_bed_reducer";
import StashMoveItemToSlotReducer from "./stash_move_item_to_slot_reducer";
import StashPullItemReducer from "./stash_pull_item_reducer";
import StashPullItemToHotbarSlotReducer from "./stash_pull_item_to_hotbar_slot_reducer";
import StashPullItemToInventorySlotReducer from "./stash_pull_item_to_inventory_slot_reducer";
import StashPushItemReducer from "./stash_push_item_reducer";
import StashPushItemToSlotReducer from "./stash_push_item_to_slot_reducer";
import SubmitFirearmShotReducer from "./submit_firearm_shot_reducer";
import SubmitMeleeSwingReducer from "./submit_melee_swing_reducer";
import SubmitPlayerLocomotionSnapshotReducer from "./submit_player_locomotion_snapshot_reducer";
import SyncOwnedApartmentStashDecorReducer from "./sync_owned_apartment_stash_decor_reducer";
import UpdateApartmentUnitDecorReducer from "./update_apartment_unit_decor_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import ApartmentDoorRow from "./apartment_door_table";
import ApartmentDoorGameplayRow from "./apartment_door_gameplay_table";
import ApartmentUnitRow from "./apartment_unit_table";
import ApartmentUnitDecorRow from "./apartment_unit_decor_table";
import ApartmentWaterTankRow from "./apartment_water_tank_table";
import ApartmentWaterTankScheduleRow from "./apartment_water_tank_schedule_table";
import BalconyGrowLightRow from "./balcony_grow_light_table";
import BalconyGrowPlantRow from "./balcony_grow_plant_table";
import BalconyGrowTickScheduleRow from "./balcony_grow_tick_schedule_table";
import BalconyGrowTrayRow from "./balcony_grow_tray_table";
import BalconyWaterPatchRow from "./balcony_water_patch_table";
import CombatSimNpcSpawnRow from "./combat_sim_npc_spawn_table";
import CraftQueueItemRow from "./craft_queue_item_table";
import CraftQueueTickRow from "./craft_queue_tick_table";
import DroppedItemRow from "./dropped_item_table";
import DroppedItemCleanupRow from "./dropped_item_cleanup_table";
import ElevatorCarRow from "./elevator_car_table";
import ElevatorLandingDoorRow from "./elevator_landing_door_table";
import FlashlightChargeRow from "./flashlight_charge_table";
import HudToastCleanupTickRow from "./hud_toast_cleanup_tick_table";
import HudToastEventRow from "./hud_toast_event_table";
import InventoryItemRow from "./inventory_item_table";
import PhysicsTickRow from "./physics_tick_table";
import PlayerActiveHotbarRow from "./player_active_hotbar_table";
import PlayerFirearmCooldownRow from "./player_firearm_cooldown_table";
import PlayerFootCadenceRow from "./player_foot_cadence_table";
import PlayerGrowJournalRow from "./player_grow_journal_table";
import PlayerInputRow from "./player_input_table";
import PlayerMeleeCooldownRow from "./player_melee_cooldown_table";
import PlayerPoseRow from "./player_pose_table";
import PlayerVitalsRow from "./player_vitals_table";
import PlayerVitalsScheduleRow from "./player_vitals_schedule_table";
import PlayerWorldProgressRow from "./player_world_progress_table";
import UserRow from "./user_table";
import WaterBottleFillRow from "./water_bottle_fill_table";
import WorldLootRefreshRow from "./world_loot_refresh_table";
import WorldNpcRow from "./world_npc_table";
import WorldNpcScheduleRow from "./world_npc_schedule_table";
import WorldSoundEventRow from "./world_sound_event_table";
import WorldSoundEventCleanupRow from "./world_sound_event_cleanup_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  apartment_door: __table({
    name: 'apartment_door',
    indexes: [
      { name: 'row_key', algorithm: 'btree', columns: [
        'rowKey',
      ] },
    ],
    constraints: [
      { name: 'apartment_door_row_key_key', constraint: 'unique', columns: ['rowKey'] },
    ],
  }, ApartmentDoorRow),
  apartment_door_gameplay: __table({
    name: 'apartment_door_gameplay',
    indexes: [
      { name: 'row_key', algorithm: 'btree', columns: [
        'rowKey',
      ] },
    ],
    constraints: [
      { name: 'apartment_door_gameplay_row_key_key', constraint: 'unique', columns: ['rowKey'] },
    ],
  }, ApartmentDoorGameplayRow),
  apartment_unit: __table({
    name: 'apartment_unit',
    indexes: [
      { name: 'unit_key', algorithm: 'btree', columns: [
        'unitKey',
      ] },
    ],
    constraints: [
      { name: 'apartment_unit_unit_key_key', constraint: 'unique', columns: ['unitKey'] },
    ],
  }, ApartmentUnitRow),
  apartment_unit_decor: __table({
    name: 'apartment_unit_decor',
    indexes: [
      { name: 'decor_id', algorithm: 'btree', columns: [
        'decorId',
      ] },
    ],
    constraints: [
      { name: 'apartment_unit_decor_decor_id_key', constraint: 'unique', columns: ['decorId'] },
    ],
  }, ApartmentUnitDecorRow),
  apartment_water_tank: __table({
    name: 'apartment_water_tank',
    indexes: [
      { name: 'unit_key', algorithm: 'btree', columns: [
        'unitKey',
      ] },
    ],
    constraints: [
      { name: 'apartment_water_tank_unit_key_key', constraint: 'unique', columns: ['unitKey'] },
    ],
  }, ApartmentWaterTankRow),
  apartment_water_tank_schedule: __table({
    name: 'apartment_water_tank_schedule',
    indexes: [
      { name: 'scheduled_id', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'apartment_water_tank_schedule_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, ApartmentWaterTankScheduleRow),
  balcony_grow_light: __table({
    name: 'balcony_grow_light',
    indexes: [
      { name: 'unit_key', algorithm: 'btree', columns: [
        'unitKey',
      ] },
    ],
    constraints: [
      { name: 'balcony_grow_light_unit_key_key', constraint: 'unique', columns: ['unitKey'] },
    ],
  }, BalconyGrowLightRow),
  balcony_grow_plant: __table({
    name: 'balcony_grow_plant',
    indexes: [
      { name: 'row_key', algorithm: 'btree', columns: [
        'rowKey',
      ] },
    ],
    constraints: [
      { name: 'balcony_grow_plant_row_key_key', constraint: 'unique', columns: ['rowKey'] },
    ],
  }, BalconyGrowPlantRow),
  balcony_grow_tick_schedule: __table({
    name: 'balcony_grow_tick_schedule',
    indexes: [
      { name: 'scheduled_id', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'balcony_grow_tick_schedule_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, BalconyGrowTickScheduleRow),
  balcony_grow_tray: __table({
    name: 'balcony_grow_tray',
    indexes: [
      { name: 'row_key', algorithm: 'btree', columns: [
        'rowKey',
      ] },
    ],
    constraints: [
      { name: 'balcony_grow_tray_row_key_key', constraint: 'unique', columns: ['rowKey'] },
    ],
  }, BalconyGrowTrayRow),
  balcony_water_patch: __table({
    name: 'balcony_water_patch',
    indexes: [
      { name: 'patch_id', algorithm: 'btree', columns: [
        'patchId',
      ] },
    ],
    constraints: [
      { name: 'balcony_water_patch_patch_id_key', constraint: 'unique', columns: ['patchId'] },
    ],
  }, BalconyWaterPatchRow),
  combat_sim_npc_spawn: __table({
    name: 'combat_sim_npc_spawn',
    indexes: [
      { name: 'row_id', algorithm: 'btree', columns: [
        'rowId',
      ] },
    ],
    constraints: [
      { name: 'combat_sim_npc_spawn_row_id_key', constraint: 'unique', columns: ['rowId'] },
    ],
  }, CombatSimNpcSpawnRow),
  craft_queue_item: __table({
    name: 'craft_queue_item',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'craft_queue_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CraftQueueItemRow),
  craft_queue_tick: __table({
    name: 'craft_queue_tick',
    indexes: [
      { name: 'scheduled_id', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'craft_queue_tick_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, CraftQueueTickRow),
  dropped_item: __table({
    name: 'dropped_item',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'dropped_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DroppedItemRow),
  dropped_item_cleanup: __table({
    name: 'dropped_item_cleanup',
    indexes: [
      { name: 'scheduled_id', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'dropped_item_cleanup_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, DroppedItemCleanupRow),
  elevator_car: __table({
    name: 'elevator_car',
    indexes: [
      { name: 'shaft_key', algorithm: 'btree', columns: [
        'shaftKey',
      ] },
    ],
    constraints: [
      { name: 'elevator_car_shaft_key_key', constraint: 'unique', columns: ['shaftKey'] },
    ],
  }, ElevatorCarRow),
  elevator_landing_door: __table({
    name: 'elevator_landing_door',
    indexes: [
      { name: 'row_key', algorithm: 'btree', columns: [
        'rowKey',
      ] },
    ],
    constraints: [
      { name: 'elevator_landing_door_row_key_key', constraint: 'unique', columns: ['rowKey'] },
    ],
  }, ElevatorLandingDoorRow),
  flashlight_charge: __table({
    name: 'flashlight_charge',
    indexes: [
      { name: 'item_instance_id', algorithm: 'btree', columns: [
        'itemInstanceId',
      ] },
    ],
    constraints: [
      { name: 'flashlight_charge_item_instance_id_key', constraint: 'unique', columns: ['itemInstanceId'] },
    ],
  }, FlashlightChargeRow),
  hud_toast_cleanup_tick: __table({
    name: 'hud_toast_cleanup_tick',
    indexes: [
      { name: 'scheduled_id', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'hud_toast_cleanup_tick_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, HudToastCleanupTickRow),
  hud_toast_event: __table({
    name: 'hud_toast_event',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'hud_toast_event_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, HudToastEventRow),
  inventory_item: __table({
    name: 'inventory_item',
    indexes: [
      { name: 'instance_id', algorithm: 'btree', columns: [
        'instanceId',
      ] },
    ],
    constraints: [
      { name: 'inventory_item_instance_id_key', constraint: 'unique', columns: ['instanceId'] },
    ],
  }, InventoryItemRow),
  physics_tick: __table({
    name: 'physics_tick',
    indexes: [
      { name: 'scheduled_id', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'physics_tick_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, PhysicsTickRow),
  player_active_hotbar: __table({
    name: 'player_active_hotbar',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_active_hotbar_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerActiveHotbarRow),
  player_firearm_cooldown: __table({
    name: 'player_firearm_cooldown',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_firearm_cooldown_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerFirearmCooldownRow),
  player_foot_cadence: __table({
    name: 'player_foot_cadence',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_foot_cadence_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerFootCadenceRow),
  player_grow_journal: __table({
    name: 'player_grow_journal',
    indexes: [
      { name: 'row_key', algorithm: 'btree', columns: [
        'rowKey',
      ] },
    ],
    constraints: [
      { name: 'player_grow_journal_row_key_key', constraint: 'unique', columns: ['rowKey'] },
    ],
  }, PlayerGrowJournalRow),
  player_input: __table({
    name: 'player_input',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_input_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerInputRow),
  player_melee_cooldown: __table({
    name: 'player_melee_cooldown',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_melee_cooldown_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerMeleeCooldownRow),
  player_pose: __table({
    name: 'player_pose',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_pose_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerPoseRow),
  player_vitals: __table({
    name: 'player_vitals',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_vitals_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerVitalsRow),
  player_vitals_schedule: __table({
    name: 'player_vitals_schedule',
    indexes: [
      { name: 'scheduled_id', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'player_vitals_schedule_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, PlayerVitalsScheduleRow),
  player_world_progress: __table({
    name: 'player_world_progress',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_world_progress_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerWorldProgressRow),
  user: __table({
    name: 'user',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'user_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UserRow),
  water_bottle_fill: __table({
    name: 'water_bottle_fill',
    indexes: [
      { name: 'item_instance_id', algorithm: 'btree', columns: [
        'itemInstanceId',
      ] },
    ],
    constraints: [
      { name: 'water_bottle_fill_item_instance_id_key', constraint: 'unique', columns: ['itemInstanceId'] },
    ],
  }, WaterBottleFillRow),
  world_loot_refresh: __table({
    name: 'world_loot_refresh',
    indexes: [
      { name: 'scheduled_id', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'world_loot_refresh_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, WorldLootRefreshRow),
  world_npc: __table({
    name: 'world_npc',
    indexes: [
      { name: 'npc_id', algorithm: 'btree', columns: [
        'npcId',
      ] },
    ],
    constraints: [
      { name: 'world_npc_npc_id_key', constraint: 'unique', columns: ['npcId'] },
    ],
  }, WorldNpcRow),
  world_npc_schedule: __table({
    name: 'world_npc_schedule',
    indexes: [
      { name: 'scheduled_id', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'world_npc_schedule_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, WorldNpcScheduleRow),
  world_sound_event: __table({
    name: 'world_sound_event',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'world_sound_event_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldSoundEventRow),
  world_sound_event_cleanup: __table({
    name: 'world_sound_event_cleanup',
    indexes: [
      { name: 'scheduled_id', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'world_sound_event_cleanup_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, WorldSoundEventCleanupRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_apartment_unit_decor", AddApartmentUnitDecorReducer),
  __reducerSchema("add_combat_sim_npc_spawn", AddCombatSimNpcSpawnReducer),
  __reducerSchema("apartment_door_set", ApartmentDoorSetReducer),
  __reducerSchema("apartment_door_toggle", ApartmentDoorToggleReducer),
  __reducerSchema("cancel_waiting_craft", CancelWaitingCraftReducer),
  __reducerSchema("claim_apartment_pulse", ClaimApartmentPulseReducer),
  __reducerSchema("clear_combat_sim_npc_spawns", ClearCombatSimNpcSpawnsReducer),
  __reducerSchema("consume_hotbar_item", ConsumeHotbarItemReducer),
  __reducerSchema("delete_apartment_unit_decor", DeleteApartmentUnitDecorReducer),
  __reducerSchema("drop_item", DropItemReducer),
  __reducerSchema("dump_water_from_bottle", DumpWaterFromBottleReducer),
  __reducerSchema("elevator_hail", ElevatorHailReducer),
  __reducerSchema("elevator_landing_exterior_door_set", ElevatorLandingExteriorDoorSetReducer),
  __reducerSchema("elevator_landing_exterior_door_toggle", ElevatorLandingExteriorDoorToggleReducer),
  __reducerSchema("elevator_select_floor", ElevatorSelectFloorReducer),
  __reducerSchema("enqueue_craft", EnqueueCraftReducer),
  __reducerSchema("enter_combat_sim", EnterCombatSimReducer),
  __reducerSchema("fill_water_bottle_at_tank", FillWaterBottleAtTankReducer),
  __reducerSchema("harvest_balcony_grow_slot", HarvestBalconyGrowSlotReducer),
  __reducerSchema("leave_combat_sim", LeaveCombatSimReducer),
  __reducerSchema("move_item_to_hotbar", MoveItemToHotbarReducer),
  __reducerSchema("move_item_to_inventory", MoveItemToInventoryReducer),
  __reducerSchema("pickup_dropped_item", PickupDroppedItemReducer),
  __reducerSchema("ping_world", PingWorldReducer),
  __reducerSchema("plant_balcony_grow_slot", PlantBalconyGrowSlotReducer),
  __reducerSchema("reinforce_apartment_pulse", ReinforceApartmentPulseReducer),
  __reducerSchema("respawn_player", RespawnPlayerReducer),
  __reducerSchema("set_active_hotbar_slot", SetActiveHotbarSlotReducer),
  __reducerSchema("set_avatar_body", SetAvatarBodyReducer),
  __reducerSchema("set_owned_apartment_piece_pose", SetOwnedApartmentPiecePoseReducer),
  __reducerSchema("set_username", SetUsernameReducer),
  __reducerSchema("sleep_in_bed", SleepInBedReducer),
  __reducerSchema("stash_move_item_to_slot", StashMoveItemToSlotReducer),
  __reducerSchema("stash_pull_item", StashPullItemReducer),
  __reducerSchema("stash_pull_item_to_hotbar_slot", StashPullItemToHotbarSlotReducer),
  __reducerSchema("stash_pull_item_to_inventory_slot", StashPullItemToInventorySlotReducer),
  __reducerSchema("stash_push_item", StashPushItemReducer),
  __reducerSchema("stash_push_item_to_slot", StashPushItemToSlotReducer),
  __reducerSchema("submit_firearm_shot", SubmitFirearmShotReducer),
  __reducerSchema("submit_melee_swing", SubmitMeleeSwingReducer),
  __reducerSchema("submit_player_locomotion_snapshot", SubmitPlayerLocomotionSnapshotReducer),
  __reducerSchema("sync_owned_apartment_stash_decor", SyncOwnedApartmentStashDecorReducer),
  __reducerSchema("update_apartment_unit_decor", UpdateApartmentUnitDecorReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.0.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

