// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.0.1 (commit a4d29daec8ed35ce4913a335b7210b9ae3933d00).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import CleanupOldDroppedItemsReducer from "./cleanup_old_dropped_items_reducer";
import CleanupOldWorldSoundEventsReducer from "./cleanup_old_world_sound_events_reducer";
import ConsumeHotbarItemReducer from "./consume_hotbar_item_reducer";
import DropItemReducer from "./drop_item_reducer";
import ElevatorHailReducer from "./elevator_hail_reducer";
import ElevatorLandingExteriorDoorToggleReducer from "./elevator_landing_exterior_door_toggle_reducer";
import ElevatorSelectFloorReducer from "./elevator_select_floor_reducer";
import MoveItemToHotbarReducer from "./move_item_to_hotbar_reducer";
import MoveItemToInventoryReducer from "./move_item_to_inventory_reducer";
import PhysicsTickStepReducer from "./physics_tick_step_reducer";
import PickupDroppedItemReducer from "./pickup_dropped_item_reducer";
import PingWorldReducer from "./ping_world_reducer";
import PlayerVitalsTickStepReducer from "./player_vitals_tick_step_reducer";
import SetActiveHotbarSlotReducer from "./set_active_hotbar_slot_reducer";
import SetUsernameReducer from "./set_username_reducer";
import SubmitMeleeSwingReducer from "./submit_melee_swing_reducer";
import SubmitMoveIntentReducer from "./submit_move_intent_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import DroppedItemRow from "./dropped_item_table";
import DroppedItemCleanupRow from "./dropped_item_cleanup_table";
import ElevatorCarRow from "./elevator_car_table";
import ElevatorLandingDoorRow from "./elevator_landing_door_table";
import InventoryItemRow from "./inventory_item_table";
import PhysicsTickRow from "./physics_tick_table";
import PlayerActiveHotbarRow from "./player_active_hotbar_table";
import PlayerFootCadenceRow from "./player_foot_cadence_table";
import PlayerInputRow from "./player_input_table";
import PlayerMeleeCooldownRow from "./player_melee_cooldown_table";
import PlayerPoseRow from "./player_pose_table";
import PlayerVitalsRow from "./player_vitals_table";
import PlayerVitalsScheduleRow from "./player_vitals_schedule_table";
import UserRow from "./user_table";
import WorldSoundEventRow from "./world_sound_event_table";
import WorldSoundEventCleanupRow from "./world_sound_event_cleanup_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  dropped_item: __table({
    name: 'dropped_item',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'dropped_item_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DroppedItemRow),
  dropped_item_cleanup: __table({
    name: 'dropped_item_cleanup',
    indexes: [
      { name: 'scheduled_id', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'dropped_item_cleanup_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, DroppedItemCleanupRow),
  elevator_car: __table({
    name: 'elevator_car',
    indexes: [
      { name: 'shaft_key', algorithm: 'btree', columns: [
        'shaftKey',
      ] },
    ],
    constraints: [
      { name: 'elevator_car_shaft_key_key', constraint: 'unique', columns: ['shaftKey'] },
    ],
  }, ElevatorCarRow),
  elevator_landing_door: __table({
    name: 'elevator_landing_door',
    indexes: [
      { name: 'row_key', algorithm: 'btree', columns: [
        'rowKey',
      ] },
    ],
    constraints: [
      { name: 'elevator_landing_door_row_key_key', constraint: 'unique', columns: ['rowKey'] },
    ],
  }, ElevatorLandingDoorRow),
  inventory_item: __table({
    name: 'inventory_item',
    indexes: [
      { name: 'instance_id', algorithm: 'btree', columns: [
        'instanceId',
      ] },
    ],
    constraints: [
      { name: 'inventory_item_instance_id_key', constraint: 'unique', columns: ['instanceId'] },
    ],
  }, InventoryItemRow),
  physics_tick: __table({
    name: 'physics_tick',
    indexes: [
      { name: 'scheduled_id', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'physics_tick_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, PhysicsTickRow),
  player_active_hotbar: __table({
    name: 'player_active_hotbar',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_active_hotbar_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerActiveHotbarRow),
  player_foot_cadence: __table({
    name: 'player_foot_cadence',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_foot_cadence_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerFootCadenceRow),
  player_input: __table({
    name: 'player_input',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_input_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerInputRow),
  player_melee_cooldown: __table({
    name: 'player_melee_cooldown',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_melee_cooldown_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerMeleeCooldownRow),
  player_pose: __table({
    name: 'player_pose',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_pose_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerPoseRow),
  player_vitals: __table({
    name: 'player_vitals',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'player_vitals_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, PlayerVitalsRow),
  player_vitals_schedule: __table({
    name: 'player_vitals_schedule',
    indexes: [
      { name: 'scheduled_id', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'player_vitals_schedule_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, PlayerVitalsScheduleRow),
  user: __table({
    name: 'user',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'user_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UserRow),
  world_sound_event: __table({
    name: 'world_sound_event',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'world_sound_event_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorldSoundEventRow),
  world_sound_event_cleanup: __table({
    name: 'world_sound_event_cleanup',
    indexes: [
      { name: 'scheduled_id', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'world_sound_event_cleanup_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, WorldSoundEventCleanupRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("cleanup_old_dropped_items", CleanupOldDroppedItemsReducer),
  __reducerSchema("cleanup_old_world_sound_events", CleanupOldWorldSoundEventsReducer),
  __reducerSchema("consume_hotbar_item", ConsumeHotbarItemReducer),
  __reducerSchema("drop_item", DropItemReducer),
  __reducerSchema("elevator_hail", ElevatorHailReducer),
  __reducerSchema("elevator_landing_exterior_door_toggle", ElevatorLandingExteriorDoorToggleReducer),
  __reducerSchema("elevator_select_floor", ElevatorSelectFloorReducer),
  __reducerSchema("move_item_to_hotbar", MoveItemToHotbarReducer),
  __reducerSchema("move_item_to_inventory", MoveItemToInventoryReducer),
  __reducerSchema("physics_tick_step", PhysicsTickStepReducer),
  __reducerSchema("pickup_dropped_item", PickupDroppedItemReducer),
  __reducerSchema("ping_world", PingWorldReducer),
  __reducerSchema("player_vitals_tick_step", PlayerVitalsTickStepReducer),
  __reducerSchema("set_active_hotbar_slot", SetActiveHotbarSlotReducer),
  __reducerSchema("set_username", SetUsernameReducer),
  __reducerSchema("submit_melee_swing", SubmitMeleeSwingReducer),
  __reducerSchema("submit_move_intent", SubmitMoveIntentReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.0.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

