// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  sleepsCount: __t.u32().name("sleeps_count"),
  timeOfDayMinutes: __t.u16().name("time_of_day_minutes"),
  awakeMinutes: __t.u32().name("awake_minutes"),
  sleepPressure: __t.f32().name("sleep_pressure"),
  lastBedTimeMinutes: __t.u16().name("last_bed_time_minutes"),
  lastSleepQuality: __t.u8().name("last_sleep_quality"),
  stimulantLoad: __t.f32().name("stimulant_load"),
  fatigueDebt: __t.f32().name("fatigue_debt"),
  stimulantChewsToday: __t.u8().name("stimulant_chews_today"),
});
