// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  activeMissionId: __t.string().name("active_mission_id"),
  status: __t.u8(),
  itemCollected: __t.bool().name("item_collected"),
  itemDeposited: __t.bool().name("item_deposited"),
  firstExtractionComplete: __t.bool().name("first_extraction_complete"),
});
