// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  yaw: __t.f32(),
  seq: __t.u64(),
  velX: __t.f32().name("vel_x"),
  velY: __t.f32().name("vel_y"),
  velZ: __t.f32().name("vel_z"),
  grounded: __t.u8(),
  meleePresentationSeq: __t.u32().name("melee_presentation_seq"),
  firearmPresentationSeq: __t.u32().name("firearm_presentation_seq"),
});
