// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const DroppedItem = __t.object("DroppedItem", {
  id: __t.u64(),
  defId: __t.string(),
  quantity: __t.u32(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  yaw: __t.f32(),
  createdAt: __t.timestamp(),
});
export type DroppedItem = __Infer<typeof DroppedItem>;

export const DroppedItemCleanup = __t.object("DroppedItemCleanup", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type DroppedItemCleanup = __Infer<typeof DroppedItemCleanup>;

export const ElevatorCar = __t.object("ElevatorCar", {
  shaftKey: __t.string(),
  currentLevel: __t.u32(),
  doorOpen01: __t.f32(),
  phase: __t.u8(),
  moveFromLevel: __t.u32(),
  moveToLevel: __t.u32(),
  moveU: __t.f32(),
  destQueue: __t.array(__t.u32()),
  cabFloorY: __t.f32(),
  doorFace: __t.u8(),
  plateX: __t.f32(),
  plateZ: __t.f32(),
});
export type ElevatorCar = __Infer<typeof ElevatorCar>;

export const HotbarLocationData = __t.object("HotbarLocationData", {
  ownerId: __t.identity(),
  slotIndex: __t.u8(),
});
export type HotbarLocationData = __Infer<typeof HotbarLocationData>;

export const InventoryItem = __t.object("InventoryItem", {
  instanceId: __t.u64(),
  defId: __t.string(),
  quantity: __t.u32(),
  get location() {
    return ItemLocation;
  },
});
export type InventoryItem = __Infer<typeof InventoryItem>;

export const InventoryLocationData = __t.object("InventoryLocationData", {
  ownerId: __t.identity(),
  slotIndex: __t.u16(),
});
export type InventoryLocationData = __Infer<typeof InventoryLocationData>;

// The tagged union or sum type for the algebraic type `ItemLocation`.
export const ItemLocation = __t.enum("ItemLocation", {
  get Inventory() {
    return InventoryLocationData;
  },
  get Hotbar() {
    return HotbarLocationData;
  },
  Unknown: __t.unit(),
});
export type ItemLocation = __Infer<typeof ItemLocation>;

export const PhysicsTick = __t.object("PhysicsTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type PhysicsTick = __Infer<typeof PhysicsTick>;

export const PlayerActiveHotbar = __t.object("PlayerActiveHotbar", {
  identity: __t.identity(),
  slotIndex: __t.u8(),
});
export type PlayerActiveHotbar = __Infer<typeof PlayerActiveHotbar>;

export const PlayerFootCadence = __t.object("PlayerFootCadence", {
  identity: __t.identity(),
  stridePhase: __t.f32(),
  lastStrideCell: __t.i32(),
  footRr: __t.u8(),
});
export type PlayerFootCadence = __Infer<typeof PlayerFootCadence>;

export const PlayerInput = __t.object("PlayerInput", {
  identity: __t.identity(),
  intentSeq: __t.u64(),
  bits: __t.u8(),
  aimYaw: __t.f32(),
});
export type PlayerInput = __Infer<typeof PlayerInput>;

export const PlayerMeleeCooldown = __t.object("PlayerMeleeCooldown", {
  identity: __t.identity(),
  lastSwingMicros: __t.i64(),
});
export type PlayerMeleeCooldown = __Infer<typeof PlayerMeleeCooldown>;

export const PlayerPose = __t.object("PlayerPose", {
  identity: __t.identity(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  yaw: __t.f32(),
  seq: __t.u64(),
  velX: __t.f32(),
  velY: __t.f32(),
  velZ: __t.f32(),
  grounded: __t.u8(),
});
export type PlayerPose = __Infer<typeof PlayerPose>;

export const PlayerVitals = __t.object("PlayerVitals", {
  identity: __t.identity(),
  health: __t.f32(),
  hunger: __t.f32(),
  hydration: __t.f32(),
  lastHotbarConsumeAt: __t.option(__t.timestamp()),
});
export type PlayerVitals = __Infer<typeof PlayerVitals>;

export const PlayerVitalsSchedule = __t.object("PlayerVitalsSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type PlayerVitalsSchedule = __Infer<typeof PlayerVitalsSchedule>;

export const User = __t.object("User", {
  identity: __t.identity(),
  username: __t.option(__t.string()),
});
export type User = __Infer<typeof User>;

export const WorldSoundEvent = __t.object("WorldSoundEvent", {
  id: __t.u64(),
  kind: __t.u8(),
  variation: __t.u8(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  volume: __t.f32(),
  maxDistanceM: __t.f32(),
  emitter: __t.identity(),
  createdAt: __t.timestamp(),
});
export type WorldSoundEvent = __Infer<typeof WorldSoundEvent>;

export const WorldSoundEventCleanup = __t.object("WorldSoundEventCleanup", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type WorldSoundEventCleanup = __Infer<typeof WorldSoundEventCleanup>;

