// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ApartmentDoor = __t.object("ApartmentDoor", {
  rowKey: __t.string(),
  floorDocId: __t.string(),
  level: __t.u32(),
  templateId: __t.string(),
  face: __t.u8(),
  hingeX: __t.f32(),
  hingeZ: __t.f32(),
  feetY: __t.f32(),
  panelWM: __t.f32(),
  panelHM: __t.f32(),
  desiredOpen: __t.u8(),
  swingOpen01: __t.f32(),
});
export type ApartmentDoor = __Infer<typeof ApartmentDoor>;

export const ApartmentDoorGameplay = __t.object("ApartmentDoorGameplay", {
  rowKey: __t.string(),
  doorHp: __t.f32(),
  breached: __t.u8(),
});
export type ApartmentDoorGameplay = __Infer<typeof ApartmentDoorGameplay>;

export const ApartmentPartitionBlocker = __t.object("ApartmentPartitionBlocker", {
  blockerId: __t.u64(),
  unitKey: __t.string(),
  minX: __t.f32(),
  minY: __t.f32(),
  minZ: __t.f32(),
  maxX: __t.f32(),
  maxY: __t.f32(),
  maxZ: __t.f32(),
});
export type ApartmentPartitionBlocker = __Infer<typeof ApartmentPartitionBlocker>;

export const ApartmentUnit = __t.object("ApartmentUnit", {
  unitKey: __t.string(),
  floorDocId: __t.string(),
  level: __t.u32(),
  unitId: __t.string(),
  state: __t.u8(),
  owner: __t.option(__t.identity()),
  claimProgressSecs: __t.f32(),
  claimStartedBy: __t.option(__t.identity()),
  lastClaimPulseMicros: __t.i64(),
  reinforceProgressSecs: __t.f32(),
  reinforceBy: __t.option(__t.identity()),
  reinforced: __t.u8(),
  bedX: __t.f32(),
  bedY: __t.f32(),
  bedZ: __t.f32(),
  bedYaw: __t.f32(),
  footX: __t.f32(),
  footY: __t.f32(),
  footZ: __t.f32(),
  wardrobeX: __t.f32(),
  wardrobeZ: __t.f32(),
  stoveX: __t.f32(),
  stoveZ: __t.f32(),
  boundMinX: __t.f32(),
  boundMaxX: __t.f32(),
  boundMinZ: __t.f32(),
  boundMaxZ: __t.f32(),
  boundMinY: __t.f32(),
  boundMaxY: __t.f32(),
});
export type ApartmentUnit = __Infer<typeof ApartmentUnit>;

export const ApartmentUnitDecor = __t.object("ApartmentUnitDecor", {
  decorId: __t.u64(),
  unitKey: __t.string(),
  modelRelPath: __t.string(),
  posX: __t.f32(),
  posY: __t.f32(),
  posZ: __t.f32(),
  yawRad: __t.f32(),
  pitchRad: __t.f32(),
  rollRad: __t.f32(),
  uniformScale: __t.f32(),
  itemKind: __t.u8(),
  authoredId: __t.string(),
});
export type ApartmentUnitDecor = __Infer<typeof ApartmentUnitDecor>;

export const ApartmentUnitUtilities = __t.object("ApartmentUnitUtilities", {
  unitKey: __t.string(),
  powerOn: __t.u8(),
  powerRestoreAfterMinutes: __t.u16(),
  waterTankOk: __t.u8(),
  waterRestoreAfterMinutes: __t.u16(),
});
export type ApartmentUnitUtilities = __Infer<typeof ApartmentUnitUtilities>;

export const ApartmentWaterTank = __t.object("ApartmentWaterTank", {
  unitKey: __t.string(),
  waterLiters: __t.f32(),
});
export type ApartmentWaterTank = __Infer<typeof ApartmentWaterTank>;

export const ApartmentWaterTankSchedule = __t.object("ApartmentWaterTankSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type ApartmentWaterTankSchedule = __Infer<typeof ApartmentWaterTankSchedule>;

export const AuthoredStashDecorSyncEntry = __t.object("AuthoredStashDecorSyncEntry", {
  authoredId: __t.string(),
  modelRelPath: __t.string(),
  itemKind: __t.u8(),
  fx: __t.f32(),
  fz: __t.f32(),
  dy: __t.f32(),
  yawRad: __t.f32(),
  pitchRad: __t.f32(),
  rollRad: __t.f32(),
  uniformScale: __t.f32(),
  linkedFishTankAuthoredId: __t.string(),
});
export type AuthoredStashDecorSyncEntry = __Infer<typeof AuthoredStashDecorSyncEntry>;

export const BalconyGrowLight = __t.object("BalconyGrowLight", {
  unitKey: __t.string(),
  lightsOn: __t.u8(),
});
export type BalconyGrowLight = __Infer<typeof BalconyGrowLight>;

export const BalconyGrowPlant = __t.object("BalconyGrowPlant", {
  rowKey: __t.string(),
  unitKey: __t.string(),
  trayId: __t.string(),
  slotIndex: __t.u8(),
  cropDefId: __t.string(),
  plantedAtMicros: __t.i64(),
  matureAtMicros: __t.i64(),
  phase: __t.u8(),
  owner: __t.identity(),
  targetDays: __t.u8(),
  daysGrown: __t.u8(),
  substrateFedOvernight: __t.u8(),
});
export type BalconyGrowPlant = __Infer<typeof BalconyGrowPlant>;

export const BalconyGrowTickSchedule = __t.object("BalconyGrowTickSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type BalconyGrowTickSchedule = __Infer<typeof BalconyGrowTickSchedule>;

export const BalconyGrowTray = __t.object("BalconyGrowTray", {
  rowKey: __t.string(),
  unitKey: __t.string(),
  trayId: __t.string(),
  posX: __t.f32(),
  posZ: __t.f32(),
  waterLiters: __t.f32(),
  dryTicks: __t.u8(),
});
export type BalconyGrowTray = __Infer<typeof BalconyGrowTray>;

export const BalconyWaterPatch = __t.object("BalconyWaterPatch", {
  patchId: __t.u64(),
  unitKey: __t.string(),
  posX: __t.f32(),
  posZ: __t.f32(),
  radiusM: __t.f32(),
  waterLiters: __t.f32(),
  createdAtMicros: __t.i64(),
  expiresAtMicros: __t.i64(),
});
export type BalconyWaterPatch = __Infer<typeof BalconyWaterPatch>;

export const CombatSimNpcSpawn = __t.object("CombatSimNpcSpawn", {
  rowId: __t.u64(),
  owner: __t.identity(),
  unitKey: __t.string(),
  archetype: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  yaw: __t.f32(),
});
export type CombatSimNpcSpawn = __Infer<typeof CombatSimNpcSpawn>;

export const CraftQueueItem = __t.object("CraftQueueItem", {
  id: __t.u64(),
  owner: __t.identity(),
  outputDefId: __t.string(),
  orderIndex: __t.u32(),
  startMicros: __t.i64(),
  finishMicros: __t.i64(),
});
export type CraftQueueItem = __Infer<typeof CraftQueueItem>;

export const CraftQueueTickSchedule = __t.object("CraftQueueTickSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type CraftQueueTickSchedule = __Infer<typeof CraftQueueTickSchedule>;

export const DroppedItem = __t.object("DroppedItem", {
  id: __t.u64(),
  defId: __t.string(),
  quantity: __t.u32(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  yaw: __t.f32(),
  createdAt: __t.timestamp(),
  worldSpawnSlot: __t.option(__t.u16()),
});
export type DroppedItem = __Infer<typeof DroppedItem>;

export const DroppedItemCleanup = __t.object("DroppedItemCleanup", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type DroppedItemCleanup = __Infer<typeof DroppedItemCleanup>;

export const ElevatorCar = __t.object("ElevatorCar", {
  shaftKey: __t.string(),
  currentLevel: __t.u32(),
  doorOpen01: __t.f32(),
  phase: __t.u8(),
  moveFromLevel: __t.u32(),
  moveToLevel: __t.u32(),
  moveU: __t.f32(),
  destQueue: __t.array(__t.u32()),
  cabFloorY: __t.f32(),
  sampleServerMicros: __t.i64(),
  doorFace: __t.u8(),
  plateX: __t.f32(),
  plateZ: __t.f32(),
});
export type ElevatorCar = __Infer<typeof ElevatorCar>;

export const ElevatorLandingDoor = __t.object("ElevatorLandingDoor", {
  rowKey: __t.string(),
  shaftKey: __t.string(),
  level: __t.u32(),
  desiredOpen: __t.u8(),
  swingOpen01: __t.f32(),
});
export type ElevatorLandingDoor = __Infer<typeof ElevatorLandingDoor>;

export const FishTankEcosystem = __t.object("FishTankEcosystem", {
  tankDecorId: __t.u64(),
  unitKey: __t.string(),
  waterLiters: __t.f32(),
  filterHealth: __t.u8(),
});
export type FishTankEcosystem = __Infer<typeof FishTankEcosystem>;

export const FishTankFilterLink = __t.object("FishTankFilterLink", {
  filterDecorId: __t.u64(),
  unitKey: __t.string(),
  tankDecorId: __t.u64(),
});
export type FishTankFilterLink = __Infer<typeof FishTankFilterLink>;

export const FishTankFilterStarterGrant = __t.object("FishTankFilterStarterGrant", {
  filterDecorId: __t.u64(),
});
export type FishTankFilterStarterGrant = __Infer<typeof FishTankFilterStarterGrant>;

export const FlashlightCharge = __t.object("FlashlightCharge", {
  itemInstanceId: __t.u64(),
  charge: __t.f32(),
});
export type FlashlightCharge = __Infer<typeof FlashlightCharge>;

export const GameTimeSchedule = __t.object("GameTimeSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type GameTimeSchedule = __Infer<typeof GameTimeSchedule>;

export const HotbarLocationData = __t.object("HotbarLocationData", {
  ownerId: __t.identity(),
  slotIndex: __t.u8(),
});
export type HotbarLocationData = __Infer<typeof HotbarLocationData>;

export const HudToastCleanupSchedule = __t.object("HudToastCleanupSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type HudToastCleanupSchedule = __Infer<typeof HudToastCleanupSchedule>;

export const HudToastEvent = __t.object("HudToastEvent", {
  id: __t.u64(),
  recipient: __t.identity(),
  toastKind: __t.u8(),
  defId: __t.string(),
  quantity: __t.u32(),
  createdAt: __t.timestamp(),
});
export type HudToastEvent = __Infer<typeof HudToastEvent>;

export const InventoryItem = __t.object("InventoryItem", {
  instanceId: __t.u64(),
  defId: __t.string(),
  quantity: __t.u32(),
  get location() {
    return ItemLocation;
  },
});
export type InventoryItem = __Infer<typeof InventoryItem>;

export const InventoryLocationData = __t.object("InventoryLocationData", {
  ownerId: __t.identity(),
  slotIndex: __t.u16(),
});
export type InventoryLocationData = __Infer<typeof InventoryLocationData>;

// The tagged union or sum type for the algebraic type `ItemLocation`.
export const ItemLocation = __t.enum("ItemLocation", {
  get Inventory() {
    return InventoryLocationData;
  },
  get Hotbar() {
    return HotbarLocationData;
  },
  get Stash() {
    return StashLocationData;
  },
  Unknown: __t.unit(),
});
export type ItemLocation = __Infer<typeof ItemLocation>;

export const PhysicsTick = __t.object("PhysicsTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type PhysicsTick = __Infer<typeof PhysicsTick>;

export const PlayerActiveHotbar = __t.object("PlayerActiveHotbar", {
  identity: __t.identity(),
  slotIndex: __t.u8(),
});
export type PlayerActiveHotbar = __Infer<typeof PlayerActiveHotbar>;

export const PlayerFirearmChamber = __t.object("PlayerFirearmChamber", {
  identity: __t.identity(),
  weaponDefId: __t.string(),
  chamberCount: __t.u8(),
  reloadCompleteMicros: __t.i64(),
});
export type PlayerFirearmChamber = __Infer<typeof PlayerFirearmChamber>;

export const PlayerFirearmCooldown = __t.object("PlayerFirearmCooldown", {
  identity: __t.identity(),
  lastShotMicros: __t.i64(),
});
export type PlayerFirearmCooldown = __Infer<typeof PlayerFirearmCooldown>;

export const PlayerFootCadence = __t.object("PlayerFootCadence", {
  identity: __t.identity(),
  stridePhase: __t.f32(),
  lastStrideCell: __t.i32(),
  footRr: __t.u8(),
});
export type PlayerFootCadence = __Infer<typeof PlayerFootCadence>;

export const PlayerGrowJournal = __t.object("PlayerGrowJournal", {
  rowKey: __t.string(),
  identity: __t.identity(),
  cropDefId: __t.string(),
});
export type PlayerGrowJournal = __Infer<typeof PlayerGrowJournal>;

export const PlayerInput = __t.object("PlayerInput", {
  identity: __t.identity(),
  intentSeq: __t.u64(),
  bits: __t.u8(),
  aimYaw: __t.f32(),
});
export type PlayerInput = __Infer<typeof PlayerInput>;

export const PlayerMeleeCooldown = __t.object("PlayerMeleeCooldown", {
  identity: __t.identity(),
  lastSwingMicros: __t.i64(),
});
export type PlayerMeleeCooldown = __Infer<typeof PlayerMeleeCooldown>;

export const PlayerMissionProgress = __t.object("PlayerMissionProgress", {
  identity: __t.identity(),
  activeMissionId: __t.string(),
  status: __t.u8(),
  itemCollected: __t.bool(),
  itemDeposited: __t.bool(),
  firstExtractionComplete: __t.bool(),
});
export type PlayerMissionProgress = __Infer<typeof PlayerMissionProgress>;

export const PlayerPose = __t.object("PlayerPose", {
  identity: __t.identity(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  yaw: __t.f32(),
  seq: __t.u64(),
  velX: __t.f32(),
  velY: __t.f32(),
  velZ: __t.f32(),
  grounded: __t.u8(),
  meleePresentationSeq: __t.u32(),
  firearmPresentationSeq: __t.u32(),
});
export type PlayerPose = __Infer<typeof PlayerPose>;

export const PlayerVitals = __t.object("PlayerVitals", {
  identity: __t.identity(),
  health: __t.f32(),
  hunger: __t.f32(),
  hydration: __t.f32(),
  lastHotbarConsumeAt: __t.option(__t.timestamp()),
});
export type PlayerVitals = __Infer<typeof PlayerVitals>;

export const PlayerVitalsSchedule = __t.object("PlayerVitalsSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type PlayerVitalsSchedule = __Infer<typeof PlayerVitalsSchedule>;

export const PlayerWeaponChamberCache = __t.object("PlayerWeaponChamberCache", {
  id: __t.u64(),
  identity: __t.identity(),
  weaponDefId: __t.string(),
  chamberCount: __t.u8(),
  reloadCompleteMicros: __t.i64(),
});
export type PlayerWeaponChamberCache = __Infer<typeof PlayerWeaponChamberCache>;

export const PlayerWorldProgress = __t.object("PlayerWorldProgress", {
  identity: __t.identity(),
  sleepsCount: __t.u32(),
  timeOfDayMinutes: __t.u16(),
  awakeMinutes: __t.u32(),
  sleepPressure: __t.f32(),
  lastBedTimeMinutes: __t.u16(),
  lastSleepQuality: __t.u8(),
  stimulantLoad: __t.f32(),
  fatigueDebt: __t.f32(),
  stimulantChewsToday: __t.u8(),
});
export type PlayerWorldProgress = __Infer<typeof PlayerWorldProgress>;

export const StashLocationData = __t.object("StashLocationData", {
  ownerIdentity: __t.identity(),
  unitKey: __t.string(),
  slotIndex: __t.u16(),
});
export type StashLocationData = __Infer<typeof StashLocationData>;

export const User = __t.object("User", {
  identity: __t.identity(),
  username: __t.option(__t.string()),
  avatarBody: __t.u8(),
});
export type User = __Infer<typeof User>;

export const WaterBottleFill = __t.object("WaterBottleFill", {
  itemInstanceId: __t.u64(),
  waterLiters: __t.f32(),
});
export type WaterBottleFill = __Infer<typeof WaterBottleFill>;

export const WorldLootRefresh = __t.object("WorldLootRefresh", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type WorldLootRefresh = __Infer<typeof WorldLootRefresh>;

export const WorldNpc = __t.object("WorldNpc", {
  npcId: __t.u64(),
  archetype: __t.string(),
  sessionKey: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  yaw: __t.f32(),
  velX: __t.f32(),
  velZ: __t.f32(),
  grounded: __t.u8(),
  health: __t.f32(),
  maxHealth: __t.f32(),
  state: __t.u8(),
  locomotion: __t.u8(),
  meleePresentationSeq: __t.u32(),
  hitPresentationSeq: __t.u32(),
  lastMeleeMicros: __t.i64(),
  chaseIdentity: __t.option(__t.identity()),
});
export type WorldNpc = __Infer<typeof WorldNpc>;

export const WorldNpcSchedule = __t.object("WorldNpcSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type WorldNpcSchedule = __Infer<typeof WorldNpcSchedule>;

export const WorldSoundEvent = __t.object("WorldSoundEvent", {
  id: __t.u64(),
  kind: __t.u8(),
  variation: __t.u8(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  volume: __t.f32(),
  maxDistanceM: __t.f32(),
  axisWeightY: __t.f32(),
  emitter: __t.identity(),
  createdAt: __t.timestamp(),
});
export type WorldSoundEvent = __Infer<typeof WorldSoundEvent>;

export const WorldSoundEventCleanup = __t.object("WorldSoundEventCleanup", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type WorldSoundEventCleanup = __Infer<typeof WorldSoundEventCleanup>;

