// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const PhysicsTick = __t.object("PhysicsTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type PhysicsTick = __Infer<typeof PhysicsTick>;

export const PlayerInput = __t.object("PlayerInput", {
  identity: __t.identity(),
  intentSeq: __t.u64(),
  bits: __t.u8(),
  aimYaw: __t.f32(),
});
export type PlayerInput = __Infer<typeof PlayerInput>;

export const PlayerPose = __t.object("PlayerPose", {
  identity: __t.identity(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  yaw: __t.f32(),
  seq: __t.u64(),
  velX: __t.f32(),
  velY: __t.f32(),
  velZ: __t.f32(),
  grounded: __t.u8(),
});
export type PlayerPose = __Infer<typeof PlayerPose>;

export const User = __t.object("User", {
  identity: __t.identity(),
  username: __t.option(__t.string()),
});
export type User = __Infer<typeof User>;

