// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  npcId: __t.u64().primaryKey().name("npc_id"),
  archetype: __t.string(),
  sessionKey: __t.string().name("session_key"),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  yaw: __t.f32(),
  velX: __t.f32().name("vel_x"),
  velZ: __t.f32().name("vel_z"),
  grounded: __t.u8(),
  health: __t.f32(),
  maxHealth: __t.f32().name("max_health"),
  state: __t.u8(),
  locomotion: __t.u8(),
  meleePresentationSeq: __t.u32().name("melee_presentation_seq"),
  hitPresentationSeq: __t.u32().name("hit_presentation_seq"),
  lastMeleeMicros: __t.i64().name("last_melee_micros"),
  chaseIdentity: __t.option(__t.identity()).name("chase_identity"),
});
