// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  rowKey: __t.string().primaryKey().name("row_key"),
  unitKey: __t.string().name("unit_key"),
  trayId: __t.string().name("tray_id"),
  slotIndex: __t.u8().name("slot_index"),
  cropDefId: __t.string().name("crop_def_id"),
  plantedAtMicros: __t.i64().name("planted_at_micros"),
  matureAtMicros: __t.i64().name("mature_at_micros"),
  phase: __t.u8(),
  owner: __t.identity(),
  targetDays: __t.u8().name("target_days"),
  daysGrown: __t.u8().name("days_grown"),
  substrateFedOvernight: __t.u8().name("substrate_fed_overnight"),
});
