// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  patchId: __t.u64().primaryKey().name("patch_id"),
  unitKey: __t.string().name("unit_key"),
  posX: __t.f32().name("pos_x"),
  posZ: __t.f32().name("pos_z"),
  radiusM: __t.f32().name("radius_m"),
  waterLiters: __t.f32().name("water_liters"),
  createdAtMicros: __t.i64().name("created_at_micros"),
  expiresAtMicros: __t.i64().name("expires_at_micros"),
});
