// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  rowKey: __t.string().primaryKey().name("row_key"),
  unitKey: __t.string().name("unit_key"),
  trayId: __t.string().name("tray_id"),
  posX: __t.f32().name("pos_x"),
  posZ: __t.f32().name("pos_z"),
  waterLiters: __t.f32().name("water_liters"),
  dryTicks: __t.u8().name("dry_ticks"),
});
