// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  kind: __t.u8(),
  variation: __t.u8(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  volume: __t.f32(),
  maxDistanceM: __t.f32().name("max_distance_m"),
  axisWeightY: __t.f32().name("axis_weight_y"),
  emitter: __t.identity(),
  createdAt: __t.timestamp().name("created_at"),
});
