// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ApartmentDoorSetReducer from "../apartment_door_set_reducer";
import ApartmentDoorToggleReducer from "../apartment_door_toggle_reducer";
import CancelWaitingCraftReducer from "../cancel_waiting_craft_reducer";
import ClaimApartmentPulseReducer from "../claim_apartment_pulse_reducer";
import CleanupOldDroppedItemsReducer from "../cleanup_old_dropped_items_reducer";
import CleanupOldHudToastsStepReducer from "../cleanup_old_hud_toasts_step_reducer";
import CleanupOldWorldSoundEventsReducer from "../cleanup_old_world_sound_events_reducer";
import ConsumeHotbarItemReducer from "../consume_hotbar_item_reducer";
import DropItemReducer from "../drop_item_reducer";
import ElevatorHailReducer from "../elevator_hail_reducer";
import ElevatorLandingExteriorDoorSetReducer from "../elevator_landing_exterior_door_set_reducer";
import ElevatorLandingExteriorDoorToggleReducer from "../elevator_landing_exterior_door_toggle_reducer";
import ElevatorSelectFloorReducer from "../elevator_select_floor_reducer";
import EnqueueCraftReducer from "../enqueue_craft_reducer";
import MoveItemToHotbarReducer from "../move_item_to_hotbar_reducer";
import MoveItemToInventoryReducer from "../move_item_to_inventory_reducer";
import OnConnectReducer from "../on_connect_reducer";
import OnDisconnectReducer from "../on_disconnect_reducer";
import PhysicsTickStepReducer from "../physics_tick_step_reducer";
import PickupDroppedItemReducer from "../pickup_dropped_item_reducer";
import PingWorldReducer from "../ping_world_reducer";
import PlayerVitalsTickStepReducer from "../player_vitals_tick_step_reducer";
import RefreshWorldLootSpawnsReducer from "../refresh_world_loot_spawns_reducer";
import ReinforceApartmentPulseReducer from "../reinforce_apartment_pulse_reducer";
import RespawnPlayerReducer from "../respawn_player_reducer";
import SetActiveHotbarSlotReducer from "../set_active_hotbar_slot_reducer";
import SetAvatarBodyReducer from "../set_avatar_body_reducer";
import SetUsernameReducer from "../set_username_reducer";
import StashMoveItemToSlotReducer from "../stash_move_item_to_slot_reducer";
import StashPullItemReducer from "../stash_pull_item_reducer";
import StashPullItemToHotbarSlotReducer from "../stash_pull_item_to_hotbar_slot_reducer";
import StashPullItemToInventorySlotReducer from "../stash_pull_item_to_inventory_slot_reducer";
import StashPushItemReducer from "../stash_push_item_reducer";
import StashPushItemToSlotReducer from "../stash_push_item_to_slot_reducer";
import SubmitFirearmShotReducer from "../submit_firearm_shot_reducer";
import SubmitMeleeSwingReducer from "../submit_melee_swing_reducer";
import SubmitPlayerLocomotionSnapshotReducer from "../submit_player_locomotion_snapshot_reducer";
import TickCraftQueueStepReducer from "../tick_craft_queue_step_reducer";

export type ApartmentDoorSetParams = __Infer<typeof ApartmentDoorSetReducer>;
export type ApartmentDoorToggleParams = __Infer<typeof ApartmentDoorToggleReducer>;
export type CancelWaitingCraftParams = __Infer<typeof CancelWaitingCraftReducer>;
export type ClaimApartmentPulseParams = __Infer<typeof ClaimApartmentPulseReducer>;
export type CleanupOldDroppedItemsParams = __Infer<typeof CleanupOldDroppedItemsReducer>;
export type CleanupOldHudToastsStepParams = __Infer<typeof CleanupOldHudToastsStepReducer>;
export type CleanupOldWorldSoundEventsParams = __Infer<typeof CleanupOldWorldSoundEventsReducer>;
export type ConsumeHotbarItemParams = __Infer<typeof ConsumeHotbarItemReducer>;
export type DropItemParams = __Infer<typeof DropItemReducer>;
export type ElevatorHailParams = __Infer<typeof ElevatorHailReducer>;
export type ElevatorLandingExteriorDoorSetParams = __Infer<typeof ElevatorLandingExteriorDoorSetReducer>;
export type ElevatorLandingExteriorDoorToggleParams = __Infer<typeof ElevatorLandingExteriorDoorToggleReducer>;
export type ElevatorSelectFloorParams = __Infer<typeof ElevatorSelectFloorReducer>;
export type EnqueueCraftParams = __Infer<typeof EnqueueCraftReducer>;
export type MoveItemToHotbarParams = __Infer<typeof MoveItemToHotbarReducer>;
export type MoveItemToInventoryParams = __Infer<typeof MoveItemToInventoryReducer>;
export type OnConnectParams = __Infer<typeof OnConnectReducer>;
export type OnDisconnectParams = __Infer<typeof OnDisconnectReducer>;
export type PhysicsTickStepParams = __Infer<typeof PhysicsTickStepReducer>;
export type PickupDroppedItemParams = __Infer<typeof PickupDroppedItemReducer>;
export type PingWorldParams = __Infer<typeof PingWorldReducer>;
export type PlayerVitalsTickStepParams = __Infer<typeof PlayerVitalsTickStepReducer>;
export type RefreshWorldLootSpawnsParams = __Infer<typeof RefreshWorldLootSpawnsReducer>;
export type ReinforceApartmentPulseParams = __Infer<typeof ReinforceApartmentPulseReducer>;
export type RespawnPlayerParams = __Infer<typeof RespawnPlayerReducer>;
export type SetActiveHotbarSlotParams = __Infer<typeof SetActiveHotbarSlotReducer>;
export type SetAvatarBodyParams = __Infer<typeof SetAvatarBodyReducer>;
export type SetUsernameParams = __Infer<typeof SetUsernameReducer>;
export type StashMoveItemToSlotParams = __Infer<typeof StashMoveItemToSlotReducer>;
export type StashPullItemParams = __Infer<typeof StashPullItemReducer>;
export type StashPullItemToHotbarSlotParams = __Infer<typeof StashPullItemToHotbarSlotReducer>;
export type StashPullItemToInventorySlotParams = __Infer<typeof StashPullItemToInventorySlotReducer>;
export type StashPushItemParams = __Infer<typeof StashPushItemReducer>;
export type StashPushItemToSlotParams = __Infer<typeof StashPushItemToSlotReducer>;
export type SubmitFirearmShotParams = __Infer<typeof SubmitFirearmShotReducer>;
export type SubmitMeleeSwingParams = __Infer<typeof SubmitMeleeSwingReducer>;
export type SubmitPlayerLocomotionSnapshotParams = __Infer<typeof SubmitPlayerLocomotionSnapshotReducer>;
export type TickCraftQueueStepParams = __Infer<typeof TickCraftQueueStepReducer>;

