/**
 * Emits `apps/server/src/generated_collision_solids/part_exterior_trees.rs` from the authoritative
 * exterior tree scatter + blocker math in `@the-mammoth/world`.
 *
 * Re-run whenever tree placement knobs / species table / blocker radii shift:
 * `pnpm content:gen-exterior-tree-collision`
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as THREE from "three";
import type { FloorDoc } from "@the-mammoth/schemas";
import {
  buildExteriorEzTreeCollisionAABBs,
  buildExteriorMegablockTreePlacements,
  EXTERIOR_PROCEDURAL_TREE_DEFAULT_COUNT,
  EXTERIOR_PROCEDURAL_TREE_DEFAULT_MAX_SCATTER_M,
  EXTERIOR_PROCEDURAL_TREE_DEFAULT_MIN_FACADE_CLEARANCE_M,
  EXTERIOR_PROCEDURAL_TREE_DEFAULT_SEED,
  instantiateBuildingFloorStack,
  parseBuildingDoc,
  parseFloorDoc,
  parseStairWellDef,
} from "../packages/world/src/index.ts";
import { mergeStaticFloorGeometries } from "../apps/client/src/game/fpSession/fpSessionStaticFloorMerge.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const mammothJson = JSON.parse(readFileSync(join(root, "content/building/mammoth.json"), "utf8"));

const stairWellJson = JSON.parse(readFileSync(join(root, "content/elevator/stairwell.json"), "utf8"));
const building = parseBuildingDoc(mammothJson as unknown);
const stairWellDef = parseStairWellDef(stairWellJson as unknown);
const floorDir = join(root, "content/building/floors");

const floorDocCache = new Map<string, FloorDoc>();
function getFloorDoc(floorDocId: string): FloorDoc {
  let doc = floorDocCache.get(floorDocId);
  if (!doc) {
    doc = parseFloorDoc(
      JSON.parse(readFileSync(join(floorDir, `${floorDocId}.json`), "utf8")) as unknown,
    );
    floorDocCache.set(floorDocId, doc);
  }
  return doc;
}

const buildingRoot = instantiateBuildingFloorStack(building, getFloorDoc, {
  stairWellDef,
});

mergeStaticFloorGeometries(buildingRoot);
buildingRoot.updateMatrixWorld(true);

const footprint = new THREE.Box3()
  .setFromObject(buildingRoot)
  .applyMatrix4(new THREE.Matrix4().copy(buildingRoot.matrixWorld).invert());
footprint.min.y = 0;
footprint.max.y = 1;

const localGroundY = buildingRoot.worldToLocal(new THREE.Vector3(0, 0, 0)).y;

const placements = buildExteriorMegablockTreePlacements(footprint, {
  count: Math.max(0, Math.floor(EXTERIOR_PROCEDURAL_TREE_DEFAULT_COUNT)),
  seed: EXTERIOR_PROCEDURAL_TREE_DEFAULT_SEED,
  minFacadeClearanceM: EXTERIOR_PROCEDURAL_TREE_DEFAULT_MIN_FACADE_CLEARANCE_M,
  maxScatterDistanceM: EXTERIOR_PROCEDURAL_TREE_DEFAULT_MAX_SCATTER_M,
});

const aabbs = buildExteriorEzTreeCollisionAABBs(placements, localGroundY);

function fmtCoord(n: number): string {
  return n.toFixed(5);
}

const rows = aabbs
  .map(
    ({ min, max }) =>
      `([${fmtCoord(min[0])}, ${fmtCoord(min[1])}, ${fmtCoord(min[2])}], [${fmtCoord(max[0])}, ${fmtCoord(max[1])}, ${fmtCoord(max[2])}])`,
  )
  .join(",\n    ");

const outPath = join(
  root,
  "apps/server/src/generated_collision_solids/part_exterior_trees.rs",
);

const header =
  "// AUTO-GENERATED by scripts/gen-exterior-tree-collision.ts — do not hand-edit.\n// Mirrors FP bootstrap (merge + plaza scatter + pillar radii) for hitscan + movement parity.\n";

const body = `${header}
static PART_EXTERIOR_PROCEDURAL_TREES: &[([f32; 3], [f32; 3])] = &[
    ${rows},
];
`;

writeFileSync(outPath, body);

console.log(
  `[gen-exterior-tree-collision] Wrote ${aabbs.length} tree collision AABB(s) → ${outPath}`,
);
