/**
 * Emits `apps/server/src/generated_walk_surfaces.rs` from authored building + floor JSON.
 * Re-run after changing floors, `worldOrigin`, or walk-surface rules in `@the-mammoth/world`.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  DEFAULT_BUILDING_FLOOR_SPACING_M,
  parseBuildingDoc,
  parseFloorDoc,
  walkSurfaceAabbXZFootprint,
  walkSurfaceAABBsForBuilding,
} from "../packages/world/src/index.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const mammoth = JSON.parse(
  readFileSync(join(root, "content/building/mammoth.json"), "utf8"),
) as unknown;
const building = parseBuildingDoc(mammoth);
const floorDir = join(root, "content/building/floors");

const aabbs = walkSurfaceAABBsForBuilding(
  building,
  (id) =>
    parseFloorDoc(
      JSON.parse(readFileSync(join(floorDir, `${id}.json`), "utf8")) as unknown,
    ),
  DEFAULT_BUILDING_FLOOR_SPACING_M,
);

const lines = aabbs.map(
  (b) =>
    `    ([${b.min.map((n) => n.toFixed(5)).join(", ")}], [${b.max.map((n) => n.toFixed(5)).join(", ")}]),`,
);

const fp = walkSurfaceAabbXZFootprint(aabbs) ?? {
  minX: 0,
  maxX: 0,
  minZ: 0,
  maxZ: 0,
};

const body = `// AUTO-GENERATED by scripts/gen-walk-aabbs.ts — do not hand-edit.
// Re-run from repo root: pnpm content:gen-walk-aabbs

pub const WALK_SURFACE_FOOTPRINT_MIN_X: f32 = ${fp.minX.toFixed(5)};
pub const WALK_SURFACE_FOOTPRINT_MAX_X: f32 = ${fp.maxX.toFixed(5)};
pub const WALK_SURFACE_FOOTPRINT_MIN_Z: f32 = ${fp.minZ.toFixed(5)};
pub const WALK_SURFACE_FOOTPRINT_MAX_Z: f32 = ${fp.maxZ.toFixed(5)};

pub static WALK_SURFACE_AABBS: &[([f32; 3], [f32; 3])] = &[
${lines.join("\n")}
];
`;

writeFileSync(join(root, "apps/server/src/generated_walk_surfaces.rs"), body);
console.log(`Wrote ${aabbs.length} walk AABBs to apps/server/src/generated_walk_surfaces.rs`);
