/**
 * Emits `apps/server/src/generated_walk_surfaces.rs` plus shard files under
 * `apps/server/src/generated_walk_surfaces/` from authored building + floor JSON.
 * Re-run after changing floors, `worldOrigin`, or walk-surface rules in `@the-mammoth/world`.
 *
 * Each shard is a full `static PART_…` item so `include!` is valid (one item per file).
 */
import { mkdirSync, readdirSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  buildFpBlockerAABBsForBuilding,
  DEFAULT_BUILDING_FLOOR_SPACING_M,
  parseBuildingDoc,
  parseFloorDoc,
  parseStairWellDef,
  walkSurfaceAabbXZFootprint,
  walkSurfaceAABBsForBuilding,
} from "../packages/world/src/index.ts";
import {
  computeWorldCollisionSourceFingerprint,
  writeWorldCollisionArtifactsStamp,
} from "./worldCollisionArtifacts.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const sourceFingerprint = computeWorldCollisionSourceFingerprint(root);

/** AABB rows per shard — keeps each generated file reviewable. */
const AABBS_PER_SHARD = 500;

const mammoth = JSON.parse(
  readFileSync(join(root, "content/building/mammoth.json"), "utf8"),
) as unknown;
const building = parseBuildingDoc(mammoth);
const stairWellDef = parseStairWellDef(
  JSON.parse(readFileSync(join(root, "content/elevator/stairwell.json"), "utf8")) as unknown,
);
const floorDir = join(root, "content/building/floors");

const aabbs = walkSurfaceAABBsForBuilding(
  building,
  (id) =>
    parseFloorDoc(
      JSON.parse(readFileSync(join(floorDir, `${id}.json`), "utf8")) as unknown,
    ),
  DEFAULT_BUILDING_FLOOR_SPACING_M,
  { stairWellDef },
);
const solidAabbs = buildFpBlockerAABBsForBuilding(
  building,
  (id) =>
    parseFloorDoc(
      JSON.parse(readFileSync(join(floorDir, `${id}.json`), "utf8")) as unknown,
    ),
  { floorSpacingM: DEFAULT_BUILDING_FLOOR_SPACING_M, stairWellDef },
);

const lines = aabbs.map(
  (b) =>
    `    ([${b.min.map((n) => n.toFixed(5)).join(", ")}], [${b.max.map((n) => n.toFixed(5)).join(", ")}]),`,
);
const solidLines = solidAabbs.map(
  (b) =>
    `    ([${b.min.map((n) => n.toFixed(5)).join(", ")}], [${b.max.map((n) => n.toFixed(5)).join(", ")}]),`,
);

const fp = walkSurfaceAabbXZFootprint(aabbs) ?? {
  minX: 0,
  maxX: 0,
  minZ: 0,
  maxZ: 0,
};
const solidFp = walkSurfaceAabbXZFootprint(solidAabbs) ?? {
  minX: 0,
  maxX: 0,
  minZ: 0,
  maxZ: 0,
};

const partsDir = join(root, "apps/server/src/generated_walk_surfaces");
mkdirSync(partsDir, { recursive: true });
for (const name of readdirSync(partsDir)) {
  if (name.startsWith("part_") && name.endsWith(".rs")) unlinkSync(join(partsDir, name));
}
for (const name of readdirSync(partsDir)) {
  if (name.endsWith(".inc")) unlinkSync(join(partsDir, name));
}

const solidsDir = join(root, "apps/server/src/generated_collision_solids");
mkdirSync(solidsDir, { recursive: true });
for (const name of readdirSync(solidsDir)) {
  if (name.startsWith("part_") && name.endsWith(".rs")) unlinkSync(join(solidsDir, name));
}

function writeShardedAabbModule(opts: {
  dir: string;
  lines: string[];
  partPrefix: string;
  title: string;
  outputFile: string;
  footprint: { minX: number; maxX: number; minZ: number; maxZ: number };
  shardConstName: string;
  footprintPrefix: string;
}) {
  const shardCount = Math.max(1, Math.ceil(opts.lines.length / AABBS_PER_SHARD));
  const partNames: string[] = [];

  for (let s = 0; s < shardCount; s++) {
    const start = s * AABBS_PER_SHARD;
    const chunk = opts.lines.slice(start, start + AABBS_PER_SHARD);
    const idx = String(s).padStart(4, "0");
    const sym = `PART_${idx}`;
    partNames.push(sym);
    const partPath = join(opts.dir, `part_${idx}.rs`);
    const partBody = `// AUTO-GENERATED by scripts/gen-walk-aabbs.ts — ${opts.title} shard ${s + 1}/${shardCount} — do not hand-edit.
static ${sym}: &[([f32; 3], [f32; 3])] = &[
${chunk.join("\n")}
];
`;
    writeFileSync(partPath, partBody, "utf8");
  }

  const includes = Array.from({ length: shardCount }, (_, s) => {
    const idx = String(s).padStart(4, "0");
    return `include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/${opts.partPrefix}/part_${idx}.rs"));`;
  }).join("\n");
  const shardRefs = partNames.map((n) => `    ${n},`).join("\n");
  const mainRs = `// AUTO-GENERATED by scripts/gen-walk-aabbs.ts — do not hand-edit.
// Re-run from repo root: pnpm content:gen-walk-aabbs

${includes}

#[allow(dead_code)]
pub const ${opts.footprintPrefix}_FOOTPRINT_MIN_X: f32 = ${opts.footprint.minX.toFixed(5)};
#[allow(dead_code)]
pub const ${opts.footprintPrefix}_FOOTPRINT_MAX_X: f32 = ${opts.footprint.maxX.toFixed(5)};
#[allow(dead_code)]
pub const ${opts.footprintPrefix}_FOOTPRINT_MIN_Z: f32 = ${opts.footprint.minZ.toFixed(5)};
#[allow(dead_code)]
pub const ${opts.footprintPrefix}_FOOTPRINT_MAX_Z: f32 = ${opts.footprint.maxZ.toFixed(5)};

/// AABBs split across shard files for reviewability.
pub static ${opts.shardConstName}: &[&[([f32; 3], [f32; 3])]] = &[
${shardRefs}
];
`;
  writeFileSync(join(root, opts.outputFile), mainRs, "utf8");
  return { shardCount };
}

function writeClientCollisionArtifactsTs(opts: {
  walkAabbs: typeof aabbs;
  walkFootprint: { minX: number; maxX: number; minZ: number; maxZ: number };
  blockerAabbs: typeof solidAabbs;
  blockerFootprint: { minX: number; maxX: number; minZ: number; maxZ: number };
}) {
  const fmtBox = (b: { min: readonly [number, number, number]; max: readonly [number, number, number] }) =>
    `  { min: [${b.min.map((n) => n.toFixed(5)).join(", ")}], max: [${b.max.map((n) => n.toFixed(5)).join(", ")}] },`;
  const out = `// AUTO-GENERATED by scripts/gen-walk-aabbs.ts — do not hand-edit.
// Re-run from repo root: pnpm content:gen-walk-aabbs

import type { CollisionAabb } from "./collisionScene.js";
import type { WalkSurfaceAabb } from "./walkSurfaceAABBs.js";

export const GENERATED_WALK_SURFACE_AABBS: readonly WalkSurfaceAabb[] = [
${opts.walkAabbs.map(fmtBox).join("\n")}
];

export const GENERATED_WALK_SURFACE_FOOTPRINT = {
  minX: ${opts.walkFootprint.minX.toFixed(5)},
  maxX: ${opts.walkFootprint.maxX.toFixed(5)},
  minZ: ${opts.walkFootprint.minZ.toFixed(5)},
  maxZ: ${opts.walkFootprint.maxZ.toFixed(5)},
} as const;

export const GENERATED_COLLISION_BLOCKER_AABBS: readonly CollisionAabb[] = [
${opts.blockerAabbs.map(fmtBox).join("\n")}
];

export const GENERATED_COLLISION_BLOCKER_FOOTPRINT = {
  minX: ${opts.blockerFootprint.minX.toFixed(5)},
  maxX: ${opts.blockerFootprint.maxX.toFixed(5)},
  minZ: ${opts.blockerFootprint.minZ.toFixed(5)},
  maxZ: ${opts.blockerFootprint.maxZ.toFixed(5)},
} as const;
`;
  writeFileSync(join(root, "packages/world/src/generatedCollisionArtifacts.ts"), out, "utf8");
}

const walkOut = writeShardedAabbModule({
  dir: partsDir,
  lines,
  partPrefix: "generated_walk_surfaces",
  title: "walk surfaces",
  outputFile: "apps/server/src/generated_walk_surfaces.rs",
  footprint: fp,
  shardConstName: "WALK_SURFACE_AABB_SHARDS",
  footprintPrefix: "WALK_SURFACE",
});
const solidOut = writeShardedAabbModule({
  dir: solidsDir,
  lines: solidLines,
  partPrefix: "generated_collision_solids",
  title: "collision solids",
  outputFile: "apps/server/src/generated_collision_solids.rs",
  footprint: solidFp,
  shardConstName: "COLLISION_SOLID_AABB_SHARDS",
  footprintPrefix: "COLLISION_SOLID",
});
writeClientCollisionArtifactsTs({
  walkAabbs: aabbs,
  walkFootprint: fp,
  blockerAabbs: solidAabbs,
  blockerFootprint: solidFp,
});
writeWorldCollisionArtifactsStamp({
  repoRoot: root,
  sourceFingerprint,
  generatedFiles: [
    "apps/server/src/generated_walk_surfaces.rs",
    "apps/server/src/generated_collision_solids.rs",
    "packages/world/src/generatedCollisionArtifacts.ts",
  ],
});
console.log(
  `Wrote ${aabbs.length} walk AABBs across ${walkOut.shardCount} shards and ${solidAabbs.length} collision AABBs across ${solidOut.shardCount} shards.`,
);
