/**
 * Emits per-floor-doc apartment-door templates as both:
 *
 * - `packages/world/src/generatedApartmentDoors.ts` (consumed by the client renderer)
 * - `apps/server/src/generated_apartment_doors.rs` (consumed by `apartment_door::init_seed`)
 *
 * Re-run from repo root: `pnpm content:gen-apartment-doors`
 *
 * The codegen runs the same `apartmentDoorTemplatesForFloor` adjacency that the floor mesh
 * pipeline already uses to carve unit-corridor wall holes, guaranteeing that every authored
 * doorway gets exactly one runtime door — no drift between the cut and the placed leaf.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  apartmentDoorTemplatesForFloor,
  FACE_CODE,
  parseBuildingDoc,
  parseFloorDoc,
  type ApartmentDoorTemplate,
} from "../packages/world/src/index.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const building = parseBuildingDoc(
  JSON.parse(readFileSync(join(root, "content/building/mammoth.json"), "utf8")) as unknown,
);
const floorDir = join(root, "content/building/floors");

const uniqueDocIds = Array.from(new Set(building.floorRefs.map((r) => r.floorDocId))).sort();

type DocBundle = { floorDocId: string; templates: ApartmentDoorTemplate[] };
const bundles: DocBundle[] = [];
let totalTemplates = 0;
for (const floorDocId of uniqueDocIds) {
  const docPath = join(floorDir, `${floorDocId}.json`);
  const doc = parseFloorDoc(JSON.parse(readFileSync(docPath, "utf8")) as unknown);
  const templates = apartmentDoorTemplatesForFloor(doc).sort((a, b) =>
    a.templateId.localeCompare(b.templateId),
  );
  bundles.push({ floorDocId, templates });
  totalTemplates += templates.length;
}

const fmtFloat = (n: number): string => n.toFixed(5);

const tsBody = `// AUTO-GENERATED by scripts/gen-apartment-door-stock.ts — do not hand-edit.
// Re-run from repo root: pnpm content:gen-apartment-doors

import type { ApartmentDoorTemplate, UnitEntryFace } from "./unitEntryAdjacency.js";

export type ApartmentDoorTemplateSet = {
  readonly floorDocId: string;
  readonly templates: readonly ApartmentDoorTemplate[];
};

export const APARTMENT_DOOR_TEMPLATES: readonly ApartmentDoorTemplateSet[] = [
${bundles
  .map(
    (b) => `  {
    floorDocId: ${JSON.stringify(b.floorDocId)},
    templates: [
${b.templates
  .map(
    (t) =>
      `      { templateId: ${JSON.stringify(t.templateId)}, unitId: ${JSON.stringify(
        t.unitId,
      )}, face: ${JSON.stringify(t.face)} as UnitEntryFace, hingeX: ${fmtFloat(t.hingeX)}, hingeZ: ${fmtFloat(
        t.hingeZ,
      )}, feetYOffset: ${fmtFloat(t.feetYOffset)}, panelWidthM: ${fmtFloat(t.panelWidthM)}, panelHeightM: ${fmtFloat(
        t.panelHeightM,
      )} },`,
  )
  .join("\n")}
    ],
  },`,
  )
  .join("\n")}
];

export const APARTMENT_DOOR_TEMPLATE_TOTAL = ${totalTemplates};
`;
writeFileSync(join(root, "packages/world/src/generatedApartmentDoors.ts"), tsBody, "utf8");

const rustBody = `// AUTO-GENERATED by scripts/gen-apartment-door-stock.ts — do not hand-edit.
// Re-run from repo root: pnpm content:gen-apartment-doors

#![allow(dead_code)]

#[derive(Clone, Copy)]
pub struct ApartmentDoorTemplate {
    pub template_id: &'static str,
    pub unit_id: &'static str,
    /// Face code (matches \`SwingDoorFace\` codes from \`@the-mammoth/world\`):
    /// 0 = N, 1 = S, 2 = E, 3 = W.
    pub face: u8,
    pub hinge_x: f32,
    pub hinge_z: f32,
    pub feet_y_offset: f32,
    pub panel_w_m: f32,
    pub panel_h_m: f32,
}

#[derive(Clone, Copy)]
pub struct ApartmentDoorTemplateSet {
    pub floor_doc_id: &'static str,
    pub templates: &'static [ApartmentDoorTemplate],
}

${bundles
  .map((b, i) => {
    const arrName = `TEMPLATES_${i}`;
    const rows = b.templates
      .map(
        (t) =>
          `    ApartmentDoorTemplate { template_id: ${JSON.stringify(
            t.templateId,
          )}, unit_id: ${JSON.stringify(t.unitId)}, face: ${
            FACE_CODE[t.face]
          }, hinge_x: ${fmtFloat(t.hingeX)}, hinge_z: ${fmtFloat(t.hingeZ)}, feet_y_offset: ${fmtFloat(
            t.feetYOffset,
          )}, panel_w_m: ${fmtFloat(t.panelWidthM)}, panel_h_m: ${fmtFloat(t.panelHeightM)} },`,
      )
      .join("\n");
    return `static ${arrName}: &[ApartmentDoorTemplate] = &[\n${rows}\n];`;
  })
  .join("\n\n")}

pub static APARTMENT_DOOR_TEMPLATE_SETS: &[ApartmentDoorTemplateSet] = &[
${bundles
  .map(
    (b, i) =>
      `    ApartmentDoorTemplateSet { floor_doc_id: ${JSON.stringify(b.floorDocId)}, templates: TEMPLATES_${i} },`,
  )
  .join("\n")}
];

pub const APARTMENT_DOOR_TEMPLATE_TOTAL: usize = ${totalTemplates};
`;
writeFileSync(join(root, "apps/server/src/generated_apartment_doors.rs"), rustBody, "utf8");

console.log(
  `Wrote ${totalTemplates} apartment-door templates across ${bundles.length} floor docs.`,
);
