/**
 * Emits `apps/server/src/generated_collision_constants.rs` from `@the-mammoth/game`
 * collision modules — single source of truth for body capsules + combat-sim arena geometry.
 *
 * Re-run from repo root: pnpm content:gen-collision-constants
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  BABUSHKA_BODY_HEIGHT_M,
  BABUSHKA_BODY_RADIUS_M,
  CAPSULE_PAIR_SURFACE_GAP_M,
  NPC_STATE_DEAD,
  PLAYER_BODY_HEIGHT_CROUCH_M,
  PLAYER_BODY_HEIGHT_STAND_M,
  PLAYER_BODY_RADIUS_M,
} from "../packages/game/src/collision/bodyCapsules.ts";
import {
  COLLISION_EPS,
  DEPENETRATE_PASSES,
  FP_CHARACTER_MAX_HORIZONTAL_SUBSTEP_M,
  FP_WALK_STEP_UP_MARGIN_M,
  HEAD_CLEARANCE_MIN_CEILING_BOTTOM_ABOVE_FEET_M,
  LOCOMOTION_BLOCKER_QUERY_PAD_M,
  LOCOMOTION_STATIC_MIN_BLOCKER_HEIGHT_M,
  SLIDE_PASSES,
  STEP_IGNORE_BELOW_FEET_M,
} from "../packages/game/src/collision/fpCapsuleLocomotion.ts";
import {
  COMBAT_SIM_ARENA_PAD_M,
  COMBAT_SIM_FALLBACK_HALF_EXTENT_M,
  COMBAT_SIM_WALL_HEIGHT_M,
  COMBAT_SIM_WALL_THICKNESS_M,
  combatSimArenaBoundsFromUnitFootprint,
  combatSimArenaObstacleAabbs,
  combatSimArenaObstacleWalkAabbs,
  combatSimArenaTerrainCollisionAabbs,
  combatSimArenaWalkSurfaceAabbs,
  type CollisionAabbLike,
} from "../packages/game/src/collision/combatSimArena.ts";
import {
  FP_WALK_FOOT_RADIUS_XZ_M,
  FP_WALK_MAX_SUPPORT_DROP_BELOW_FEET_M,
  FP_WALK_PROBE_DY_M,
} from "../packages/game/src/collision/walkSurfaceReach.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const outPath = join(root, "apps/server/src/generated_collision_constants.rs");

/** Floor walk slab feet inset — matches TS `combatSimArenaCollisionAabbs`. */
const COMBAT_SIM_FLOOR_WALK_INSET_Y_M = 0.12;

function f32(n: number): string {
  const s = n.toFixed(5);
  return s.includes(".") ? s : `${s}.0`;
}

function formatAabbConst(name: string, aabbs: readonly CollisionAabbLike[]): string {
  if (aabbs.length === 0) {
    return `pub const ${name}: &[([f32; 3], [f32; 3])] = &[];`;
  }
  const rows = aabbs
    .map(
      (a) =>
        `    ([${f32(a.min[0])}, ${f32(a.min[1])}, ${f32(a.min[2])}], [${f32(a.max[0])}, ${f32(a.max[1])}, ${f32(a.max[2])}]),`,
    )
    .join("\n");
  return `pub const ${name}: &[([f32; 3], [f32; 3])] = &[\n${rows}\n];`;
}

function relativeAabbs(
  aabbs: readonly CollisionAabbLike[],
  cx: number,
  footY: number,
  cz: number,
): CollisionAabbLike[] {
  return aabbs.map((a) => ({
    min: [a.min[0] - cx, a.min[1] - footY, a.min[2] - cz] as const,
    max: [a.max[0] - cx, a.max[1] - footY, a.max[2] - cz] as const,
  }));
}

/** Canonical arena at origin — geometry offsets are translated per unit at runtime. */
const canonBounds = combatSimArenaBoundsFromUnitFootprint({
  boundMinX: -COMBAT_SIM_FALLBACK_HALF_EXTENT_M,
  boundMaxX: COMBAT_SIM_FALLBACK_HALF_EXTENT_M,
  boundMinZ: -COMBAT_SIM_FALLBACK_HALF_EXTENT_M,
  boundMaxZ: COMBAT_SIM_FALLBACK_HALF_EXTENT_M,
  footY: 0,
});
const canonCx = (canonBounds.minX + canonBounds.maxX) * 0.5;
const canonCz = (canonBounds.minZ + canonBounds.maxZ) * 0.5;

const canonWalk = combatSimArenaWalkSurfaceAabbs(canonBounds);
const terrainWalkRel = relativeAabbs(canonWalk.slice(1), canonCx, 0, canonCz);
const obstacleWalkRel = relativeAabbs(
  combatSimArenaObstacleWalkAabbs(canonBounds),
  canonCx,
  0,
  canonCz,
);
const terrainCollisionRel = relativeAabbs(
  combatSimArenaTerrainCollisionAabbs(canonBounds),
  canonCx,
  0,
  canonCz,
);
const obstacleCollisionRel = relativeAabbs(
  combatSimArenaObstacleAabbs(canonBounds),
  canonCx,
  0,
  canonCz,
);

const rs = `// AUTO-GENERATED by scripts/gen-collision-constants.ts — do not hand-edit.
// Source: packages/game/src/collision/{bodyCapsules,combatSimArena,walkSurfaceReach}.ts
// Re-run from repo root: pnpm content:gen-collision-constants

// --- Body capsules (packages/game/src/collision/bodyCapsules.ts) ---

pub const PLAYER_BODY_RADIUS_M: f32 = ${f32(PLAYER_BODY_RADIUS_M)};
pub const PLAYER_BODY_HEIGHT_STAND_M: f32 = ${f32(PLAYER_BODY_HEIGHT_STAND_M)};
pub const PLAYER_BODY_HEIGHT_CROUCH_M: f32 = ${f32(PLAYER_BODY_HEIGHT_CROUCH_M)};

pub const BABUSHKA_BODY_RADIUS_M: f32 = ${f32(BABUSHKA_BODY_RADIUS_M)};
pub const BABUSHKA_BODY_HEIGHT_M: f32 = ${f32(BABUSHKA_BODY_HEIGHT_M)};

pub const CAPSULE_PAIR_SURFACE_GAP_M: f32 = ${f32(CAPSULE_PAIR_SURFACE_GAP_M)};

pub const NPC_STATE_DEAD: u8 = ${NPC_STATE_DEAD};

// --- Capsule locomotion tuning (packages/game/src/collision/fpCapsuleLocomotion.ts) ---

pub const COLLISION_EPS: f32 = ${f32(COLLISION_EPS)};
pub const STEP_IGNORE_BELOW_FEET_M: f32 = ${f32(STEP_IGNORE_BELOW_FEET_M)};
pub const FP_CHARACTER_MAX_HORIZONTAL_SUBSTEP_M: f32 = ${f32(FP_CHARACTER_MAX_HORIZONTAL_SUBSTEP_M)};
pub const SLIDE_PASSES: usize = ${SLIDE_PASSES};
pub const DEPENETRATE_PASSES: usize = ${DEPENETRATE_PASSES};
pub const FP_WALK_STEP_UP_MARGIN_M: f32 = ${f32(FP_WALK_STEP_UP_MARGIN_M)};
pub const HEAD_CLEARANCE_MIN_CEILING_BOTTOM_ABOVE_FEET_M: f32 = ${f32(HEAD_CLEARANCE_MIN_CEILING_BOTTOM_ABOVE_FEET_M)};
pub const LOCOMOTION_BLOCKER_QUERY_PAD_M: f32 = ${f32(LOCOMOTION_BLOCKER_QUERY_PAD_M)};
pub const LOCOMOTION_STATIC_MIN_BLOCKER_HEIGHT_M: f32 = ${f32(LOCOMOTION_STATIC_MIN_BLOCKER_HEIGHT_M)};

// --- Walk surface reach (packages/game/src/collision/walkSurfaceReach.ts) ---

pub const FP_WALK_FOOT_RADIUS_XZ_M: f32 = ${f32(FP_WALK_FOOT_RADIUS_XZ_M)};
pub const FP_WALK_PROBE_DY_M: f32 = ${f32(FP_WALK_PROBE_DY_M)};
pub const FP_WALK_MAX_SUPPORT_DROP_BELOW_FEET_M: f32 = ${f32(FP_WALK_MAX_SUPPORT_DROP_BELOW_FEET_M)};

// --- Combat sim arena (packages/game/src/collision/combatSimArena.ts) ---

pub const COMBAT_SIM_FALLBACK_HALF_EXTENT_M: f32 = ${f32(COMBAT_SIM_FALLBACK_HALF_EXTENT_M)};
pub const COMBAT_SIM_ARENA_PAD_M: f32 = ${f32(COMBAT_SIM_ARENA_PAD_M)};
pub const COMBAT_SIM_WALL_HEIGHT_M: f32 = ${f32(COMBAT_SIM_WALL_HEIGHT_M)};
pub const COMBAT_SIM_WALL_THICKNESS_M: f32 = ${f32(COMBAT_SIM_WALL_THICKNESS_M)};
pub const COMBAT_SIM_FLOOR_WALK_INSET_Y_M: f32 = ${f32(COMBAT_SIM_FLOOR_WALK_INSET_Y_M)};

${formatAabbConst("COMBAT_SIM_TERRAIN_WALK_AABBS_REL", terrainWalkRel)}

${formatAabbConst("COMBAT_SIM_OBSTACLE_WALK_AABBS_REL", obstacleWalkRel)}

${formatAabbConst("COMBAT_SIM_TERRAIN_COLLISION_AABBS_REL", terrainCollisionRel)}

${formatAabbConst("COMBAT_SIM_OBSTACLE_COLLISION_AABBS_REL", obstacleCollisionRel)}

#[inline]
fn translate_aabb_rel(
    mn: [f32; 3],
    mx: [f32; 3],
    cx: f32,
    foot_y: f32,
    cz: f32,
) -> ([f32; 3], [f32; 3]) {
    (
        [mn[0] + cx, mn[1] + foot_y, mn[2] + cz],
        [mx[0] + cx, mx[1] + foot_y, mx[2] + cz],
    )
}

#[inline]
fn walk_surface_top_is_reachable(
    top: f32,
    feet_y: f32,
    probe_top_y: f32,
    descent_probe: bool,
) -> bool {
    if descent_probe {
        return top <= probe_top_y + 1e-3 && top >= feet_y - FP_WALK_MAX_SUPPORT_DROP_BELOW_FEET_M;
    }
    top <= feet_y + FP_WALK_STEP_UP_MARGIN_M
}

fn sample_walk_top_from_slabs(
    slabs: &[([f32; 3], [f32; 3])],
    x: f32,
    z: f32,
    probe_feet_y: f32,
    probe_top_y: f32,
    descent_probe: bool,
) -> f32 {
    let foot_r = FP_WALK_FOOT_RADIUS_XZ_M;
    let fx0 = x - foot_r;
    let fx1 = x + foot_r;
    let fz0 = z - foot_r;
    let fz1 = z + foot_r;
    let mut best = f32::NAN;
    for (mn, mx) in slabs {
        if fx1 < mn[0] || fx0 > mx[0] || fz1 < mn[2] || fz0 > mx[2] {
            continue;
        }
        let top = mx[1];
        if !walk_surface_top_is_reachable(top, probe_feet_y, probe_top_y, descent_probe) {
            continue;
        }
        best = if best.is_nan() {
            top
        } else {
            best.max(top)
        };
    }
    best
}

fn append_translated_slabs(
    out: &mut Vec<([f32; 3], [f32; 3])>,
    rel: &[([f32; 3], [f32; 3])],
    cx: f32,
    foot_y: f32,
    cz: f32,
) {
    for (mn, mx) in rel {
        out.push(translate_aabb_rel(*mn, *mx, cx, foot_y, cz));
    }
}

fn combat_sim_arena_walk_surface_aabbs_for_unit_bounds(
    bound_min_x: f32,
    bound_max_x: f32,
    bound_min_z: f32,
    bound_max_z: f32,
    foot_y: f32,
) -> Vec<([f32; 3], [f32; 3])> {
    let min_x = bound_min_x - COMBAT_SIM_ARENA_PAD_M;
    let max_x = bound_max_x + COMBAT_SIM_ARENA_PAD_M;
    let min_z = bound_min_z - COMBAT_SIM_ARENA_PAD_M;
    let max_z = bound_max_z + COMBAT_SIM_ARENA_PAD_M;
    let cx = (min_x + max_x) * 0.5;
    let cz = (min_z + max_z) * 0.5;
    let mut out = vec![(
        [min_x, foot_y - COMBAT_SIM_FLOOR_WALK_INSET_Y_M, min_z],
        [max_x, foot_y, max_z],
    )];
    append_translated_slabs(&mut out, COMBAT_SIM_TERRAIN_WALK_AABBS_REL, cx, foot_y, cz);
    append_translated_slabs(&mut out, COMBAT_SIM_OBSTACLE_WALK_AABBS_REL, cx, foot_y, cz);
    out
}

/// Perimeter walls + floor walk + authored cover + terrain — lockstep with TS \`combatSimArenaCollisionAabbs\`.
pub fn combat_sim_arena_collision_aabbs_for_unit_bounds(
    bound_min_x: f32,
    bound_max_x: f32,
    bound_min_z: f32,
    bound_max_z: f32,
    foot_y: f32,
) -> Vec<([f32; 3], [f32; 3])> {
    let min_x = bound_min_x - COMBAT_SIM_ARENA_PAD_M;
    let max_x = bound_max_x + COMBAT_SIM_ARENA_PAD_M;
    let min_z = bound_min_z - COMBAT_SIM_ARENA_PAD_M;
    let max_z = bound_max_z + COMBAT_SIM_ARENA_PAD_M;
    let wall_y1 = foot_y + COMBAT_SIM_WALL_HEIGHT_M;
    let t = COMBAT_SIM_WALL_THICKNESS_M;
    let cx = (min_x + max_x) * 0.5;
    let cz = (min_z + max_z) * 0.5;
    let mut out = vec![
        (
            [min_x, foot_y - COMBAT_SIM_FLOOR_WALK_INSET_Y_M, min_z],
            [max_x, foot_y, max_z],
        ),
        ([min_x, foot_y, min_z], [min_x + t, wall_y1, max_z]),
        ([max_x - t, foot_y, min_z], [max_x, wall_y1, max_z]),
        ([min_x, foot_y, min_z], [max_x, wall_y1, min_z + t]),
        ([min_x, foot_y, max_z - t], [max_x, wall_y1, max_z]),
    ];
    append_translated_slabs(&mut out, COMBAT_SIM_OBSTACLE_COLLISION_AABBS_REL, cx, foot_y, cz);
    append_translated_slabs(&mut out, COMBAT_SIM_TERRAIN_COLLISION_AABBS_REL, cx, foot_y, cz);
    out
}

/// Highest walk top under probe feet — mirrors client walk spatial index + foot radius.
pub fn combat_sim_sample_walk_top_y_for_unit_bounds(
    bound_min_x: f32,
    bound_max_x: f32,
    bound_min_z: f32,
    bound_max_z: f32,
    foot_y: f32,
    x: f32,
    z: f32,
    probe_feet_y: f32,
) -> f32 {
    let slabs = combat_sim_arena_walk_surface_aabbs_for_unit_bounds(
        bound_min_x,
        bound_max_x,
        bound_min_z,
        bound_max_z,
        foot_y,
    );
    let probe_top_y = probe_feet_y + FP_WALK_PROBE_DY_M;
    let top = sample_walk_top_from_slabs(&slabs, x, z, probe_feet_y, probe_top_y, false);
    if top.is_finite() {
        return top;
    }
    let mut best = foot_y;
    for (mn, mx) in slabs {
        if x < mn[0] || x > mx[0] || z < mn[2] || z > mx[2] {
            continue;
        }
        let slab_top = mx[1];
        if slab_top <= probe_feet_y + FP_WALK_STEP_UP_MARGIN_M + 1e-4
            && slab_top >= probe_feet_y - STEP_IGNORE_BELOW_FEET_M - 1e-4
            && slab_top > best
        {
            best = slab_top;
        }
    }
    best
}
`;

writeFileSync(outPath, rs, "utf8");
console.log(`Wrote ${outPath}`);
