import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  BuildingDocSchema,
  FloorDocSchema,
  StairWellDefSchema,
} from "../packages/schemas/src/index.ts";
import { DEFAULT_BUILDING_FLOOR_SPACING_M } from "../packages/world/src/buildingFloorStack.js";
import {
  buildStairRuntimeOverlayForBuilding,
  type RuntimeStairSupportSurface,
} from "../packages/world/src/stairRuntimeOverlay.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");
const outPath = process.argv[2];

if (!outPath) {
  throw new Error("expected output path: tsx scripts/gen-stair-runtime-overlay.ts <outPath>");
}

const building = BuildingDocSchema.parse(
  JSON.parse(readFileSync(join(repoRoot, "content/building/mammoth.json"), "utf8")) as unknown,
);
const stairWellDef = StairWellDefSchema.parse(
  JSON.parse(readFileSync(join(repoRoot, "content/elevator/stairwell.json"), "utf8")) as unknown,
);
const floorDir = join(repoRoot, "content/building/floors");
const overlay = buildStairRuntimeOverlayForBuilding(
  building,
  (id) =>
    FloorDocSchema.parse(
      JSON.parse(readFileSync(join(floorDir, `${id}.json`), "utf8")) as unknown,
    ),
  stairWellDef,
  DEFAULT_BUILDING_FLOOR_SPACING_M,
);

const fmtAabb = (aabb: { min: readonly [number, number, number]; max: readonly [number, number, number] }) =>
  `    ([${aabb.min.map((n) => n.toFixed(5)).join(", ")}], [${aabb.max.map((n) => n.toFixed(5)).join(", ")}]),`;

const fmtSurface = (surface: RuntimeStairSupportSurface) => {
  if (surface.kind === "flat") {
    return `    RuntimeStairSupportSurface::Flat { min_x: ${surface.minX.toFixed(5)}, max_x: ${surface.maxX.toFixed(5)}, min_z: ${surface.minZ.toFixed(5)}, max_z: ${surface.maxZ.toFixed(5)}, top_y: ${surface.topY.toFixed(5)} },`;
  }
  return `    RuntimeStairSupportSurface::Slope { axis: b'${surface.axis}', min_x: ${surface.minX.toFixed(5)}, max_x: ${surface.maxX.toFixed(5)}, min_z: ${surface.minZ.toFixed(5)}, max_z: ${surface.maxZ.toFixed(5)}, along_min: ${surface.alongMin.toFixed(5)}, along_max: ${surface.alongMax.toFixed(5)}, y_at_along_min: ${surface.yAtAlongMin.toFixed(5)}, y_at_along_max: ${surface.yAtAlongMax.toFixed(5)} },`;
};

const body = `// AUTO-GENERATED by scripts/gen-stair-runtime-overlay.ts — do not hand-edit.
static STAIR_RUNTIME_BLOCKER_SUPPRESS_MASKS: &[([f32; 3], [f32; 3])] = &[
${overlay.blockerSuppressMasks.map(fmtAabb).join("\n")}
];

static STAIR_RUNTIME_BLOCKER_REPLACEMENTS: &[([f32; 3], [f32; 3])] = &[
${overlay.blockerReplacementAabbs.map(fmtAabb).join("\n")}
];

static STAIR_RUNTIME_WALK_SUPPRESS_MASKS: &[([f32; 3], [f32; 3])] = &[
${overlay.walkSuppressMasks.map(fmtAabb).join("\n")}
];

static STAIR_RUNTIME_SUPPORT_SURFACES: &[RuntimeStairSupportSurface] = &[
${overlay.supportSurfaces.map(fmtSurface).join("\n")}
];
`;

writeFileSync(outPath, body, "utf8");
