/**
 * Emits `apps/server/src/generated_collision_constants.rs` from `@the-mammoth/game`
 * collision modules — single source of truth for body capsules + combat-sim arena tuning.
 *
 * Re-run from repo root: pnpm content:gen-collision-constants
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  BABUSHKA_BODY_HEIGHT_M,
  BABUSHKA_BODY_RADIUS_M,
  CAPSULE_PAIR_SURFACE_GAP_M,
  NPC_STATE_DEAD,
  PLAYER_BODY_HEIGHT_CROUCH_M,
  PLAYER_BODY_HEIGHT_STAND_M,
  PLAYER_BODY_RADIUS_M,
} from "../packages/game/src/collision/bodyCapsules.ts";
import {
  COLLISION_EPS,
  DEPENETRATE_PASSES,
  FP_CHARACTER_MAX_HORIZONTAL_SUBSTEP_M,
  FP_WALK_STEP_UP_MARGIN_M,
  HEAD_CLEARANCE_MIN_CEILING_BOTTOM_ABOVE_FEET_M,
  LOCOMOTION_BLOCKER_QUERY_PAD_M,
  LOCOMOTION_STATIC_MIN_BLOCKER_HEIGHT_M,
  SLIDE_PASSES,
  STEP_IGNORE_BELOW_FEET_M,
} from "../packages/game/src/collision/fpCapsuleLocomotion.ts";
import {
  COMBAT_SIM_ARENA_PAD_M,
  COMBAT_SIM_AUTHORED_OBSTACLES,
  COMBAT_SIM_FALLBACK_HALF_EXTENT_M,
  COMBAT_SIM_WALL_HEIGHT_M,
  COMBAT_SIM_WALL_THICKNESS_M,
} from "../packages/game/src/collision/combatSimArena.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const outPath = join(root, "apps/server/src/generated_collision_constants.rs");

function f32(n: number): string {
  const s = n.toFixed(5);
  return s.includes(".") ? s : `${s}.0`;
}

const obstacleRows = COMBAT_SIM_AUTHORED_OBSTACLES.map(
  (o) =>
    `    CombatSimObstacleSpec {
        center_off_x: ${f32(o.centerOffsetX)},
        center_off_z: ${f32(o.centerOffsetZ)},
        size_x: ${f32(o.sizeX)},
        size_y: ${f32(o.sizeY)},
        size_z: ${f32(o.sizeZ)},
    },`,
).join("\n");

const rs = `// AUTO-GENERATED by scripts/gen-collision-constants.ts — do not hand-edit.
// Source: packages/game/src/collision/{bodyCapsules,combatSimArena}.ts
// Re-run from repo root: pnpm content:gen-collision-constants

// --- Body capsules (packages/game/src/collision/bodyCapsules.ts) ---

pub const PLAYER_BODY_RADIUS_M: f32 = ${f32(PLAYER_BODY_RADIUS_M)};
pub const PLAYER_BODY_HEIGHT_STAND_M: f32 = ${f32(PLAYER_BODY_HEIGHT_STAND_M)};
pub const PLAYER_BODY_HEIGHT_CROUCH_M: f32 = ${f32(PLAYER_BODY_HEIGHT_CROUCH_M)};

pub const BABUSHKA_BODY_RADIUS_M: f32 = ${f32(BABUSHKA_BODY_RADIUS_M)};
pub const BABUSHKA_BODY_HEIGHT_M: f32 = ${f32(BABUSHKA_BODY_HEIGHT_M)};

pub const CAPSULE_PAIR_SURFACE_GAP_M: f32 = ${f32(CAPSULE_PAIR_SURFACE_GAP_M)};

pub const NPC_STATE_DEAD: u8 = ${NPC_STATE_DEAD};

// --- Capsule locomotion tuning (packages/game/src/collision/fpCapsuleLocomotion.ts) ---

pub const COLLISION_EPS: f32 = ${f32(COLLISION_EPS)};
pub const STEP_IGNORE_BELOW_FEET_M: f32 = ${f32(STEP_IGNORE_BELOW_FEET_M)};
pub const FP_CHARACTER_MAX_HORIZONTAL_SUBSTEP_M: f32 = ${f32(FP_CHARACTER_MAX_HORIZONTAL_SUBSTEP_M)};
pub const SLIDE_PASSES: usize = ${SLIDE_PASSES};
pub const DEPENETRATE_PASSES: usize = ${DEPENETRATE_PASSES};
pub const FP_WALK_STEP_UP_MARGIN_M: f32 = ${f32(FP_WALK_STEP_UP_MARGIN_M)};
pub const HEAD_CLEARANCE_MIN_CEILING_BOTTOM_ABOVE_FEET_M: f32 = ${f32(HEAD_CLEARANCE_MIN_CEILING_BOTTOM_ABOVE_FEET_M)};
pub const LOCOMOTION_BLOCKER_QUERY_PAD_M: f32 = ${f32(LOCOMOTION_BLOCKER_QUERY_PAD_M)};
pub const LOCOMOTION_STATIC_MIN_BLOCKER_HEIGHT_M: f32 = ${f32(LOCOMOTION_STATIC_MIN_BLOCKER_HEIGHT_M)};

// --- Combat sim arena (packages/game/src/collision/combatSimArena.ts) ---

pub const COMBAT_SIM_FALLBACK_HALF_EXTENT_M: f32 = ${f32(COMBAT_SIM_FALLBACK_HALF_EXTENT_M)};
pub const COMBAT_SIM_ARENA_PAD_M: f32 = ${f32(COMBAT_SIM_ARENA_PAD_M)};
pub const COMBAT_SIM_WALL_HEIGHT_M: f32 = ${f32(COMBAT_SIM_WALL_HEIGHT_M)};
pub const COMBAT_SIM_WALL_THICKNESS_M: f32 = ${f32(COMBAT_SIM_WALL_THICKNESS_M)};

/// Floor walk slab feet inset — matches TS \`combatSimArenaCollisionAabbs\`.
pub const COMBAT_SIM_FLOOR_WALK_INSET_Y_M: f32 = 0.12;

#[derive(Clone, Copy, Debug)]
pub struct CombatSimObstacleSpec {
    pub center_off_x: f32,
    pub center_off_z: f32,
    pub size_x: f32,
    pub size_y: f32,
    pub size_z: f32,
}

pub const COMBAT_SIM_AUTHORED_OBSTACLES: &[CombatSimObstacleSpec] = &[
${obstacleRows}
];

/// Perimeter walls + floor walk + authored cover — lockstep with TS \`combatSimArenaCollisionAabbs\`.
pub fn combat_sim_arena_collision_aabbs_for_unit_bounds(
    bound_min_x: f32,
    bound_max_x: f32,
    bound_min_z: f32,
    bound_max_z: f32,
    foot_y: f32,
) -> Vec<([f32; 3], [f32; 3])> {
    let min_x = bound_min_x - COMBAT_SIM_ARENA_PAD_M;
    let max_x = bound_max_x + COMBAT_SIM_ARENA_PAD_M;
    let min_z = bound_min_z - COMBAT_SIM_ARENA_PAD_M;
    let max_z = bound_max_z + COMBAT_SIM_ARENA_PAD_M;
    let wall_y1 = foot_y + COMBAT_SIM_WALL_HEIGHT_M;
    let t = COMBAT_SIM_WALL_THICKNESS_M;
    let mut out = vec![
        (
            [min_x, foot_y - COMBAT_SIM_FLOOR_WALK_INSET_Y_M, min_z],
            [max_x, foot_y, max_z],
        ),
        ([min_x, foot_y, min_z], [min_x + t, wall_y1, max_z]),
        ([max_x - t, foot_y, min_z], [max_x, wall_y1, max_z]),
        ([min_x, foot_y, min_z], [max_x, wall_y1, min_z + t]),
        ([min_x, foot_y, max_z - t], [max_x, wall_y1, max_z]),
    ];
    let cx = (min_x + max_x) * 0.5;
    let cz = (min_z + max_z) * 0.5;
    for spec in COMBAT_SIM_AUTHORED_OBSTACLES {
        let ox = cx + spec.center_off_x;
        let oz = cz + spec.center_off_z;
        let hx = spec.size_x * 0.5;
        let hy = spec.size_y;
        let hz = spec.size_z * 0.5;
        out.push((
            [ox - hx, foot_y, oz - hz],
            [ox + hx, foot_y + hy, oz + hz],
        ));
    }
    out
}
`;

writeFileSync(outPath, rs, "utf8");
console.log(`Wrote ${outPath}`);
