/**
 * Emits `apps/server/src/generated_walk_surfaces.rs` plus shard files under
 * `apps/server/src/generated_walk_surfaces/` from authored building + floor JSON.
 * Re-run after changing floors, `worldOrigin`, or walk-surface rules in `@the-mammoth/world`.
 *
 * Each shard is a full `static PART_…` item so `include!` is valid (one item per file).
 */
import { mkdirSync, readdirSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  DEFAULT_BUILDING_FLOOR_SPACING_M,
  parseBuildingDoc,
  parseFloorDoc,
  walkSurfaceAabbXZFootprint,
  walkSurfaceAABBsForBuilding,
} from "../packages/world/src/index.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

/** AABB rows per shard — keeps each generated file reviewable. */
const AABBS_PER_SHARD = 500;

const mammoth = JSON.parse(
  readFileSync(join(root, "content/building/mammoth.json"), "utf8"),
) as unknown;
const building = parseBuildingDoc(mammoth);
const floorDir = join(root, "content/building/floors");

const aabbs = walkSurfaceAABBsForBuilding(
  building,
  (id) =>
    parseFloorDoc(
      JSON.parse(readFileSync(join(floorDir, `${id}.json`), "utf8")) as unknown,
    ),
  DEFAULT_BUILDING_FLOOR_SPACING_M,
);

const lines = aabbs.map(
  (b) =>
    `    ([${b.min.map((n) => n.toFixed(5)).join(", ")}], [${b.max.map((n) => n.toFixed(5)).join(", ")}]),`,
);

const fp = walkSurfaceAabbXZFootprint(aabbs) ?? {
  minX: 0,
  maxX: 0,
  minZ: 0,
  maxZ: 0,
};

const partsDir = join(root, "apps/server/src/generated_walk_surfaces");
mkdirSync(partsDir, { recursive: true });
for (const name of readdirSync(partsDir)) {
  if (name.startsWith("part_") && name.endsWith(".rs")) unlinkSync(join(partsDir, name));
}
for (const name of readdirSync(partsDir)) {
  if (name.endsWith(".inc")) unlinkSync(join(partsDir, name));
}

const shardCount = Math.max(1, Math.ceil(lines.length / AABBS_PER_SHARD));
const partNames: string[] = [];

for (let s = 0; s < shardCount; s++) {
  const start = s * AABBS_PER_SHARD;
  const chunk = lines.slice(start, start + AABBS_PER_SHARD);
  const idx = String(s).padStart(4, "0");
  const sym = `PART_${idx}`;
  partNames.push(sym);
  const partPath = join(partsDir, `part_${idx}.rs`);
  const partBody = `// AUTO-GENERATED by scripts/gen-walk-aabbs.ts — shard ${s + 1}/${shardCount} — do not hand-edit.
static ${sym}: &[([f32; 3], [f32; 3])] = &[
${chunk.join("\n")}
];
`;
  writeFileSync(partPath, partBody, "utf8");
}

const includes = Array.from({ length: shardCount }, (_, s) => {
  const idx = String(s).padStart(4, "0");
  return `include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/generated_walk_surfaces/part_${idx}.rs"));`;
}).join("\n");

const shardRefs = partNames.map((n) => `    ${n},`).join("\n");

const mainRs = `// AUTO-GENERATED by scripts/gen-walk-aabbs.ts — do not hand-edit.
// Re-run from repo root: pnpm content:gen-walk-aabbs

${includes}

pub const WALK_SURFACE_FOOTPRINT_MIN_X: f32 = ${fp.minX.toFixed(5)};
pub const WALK_SURFACE_FOOTPRINT_MAX_X: f32 = ${fp.maxX.toFixed(5)};
pub const WALK_SURFACE_FOOTPRINT_MIN_Z: f32 = ${fp.minZ.toFixed(5)};
pub const WALK_SURFACE_FOOTPRINT_MAX_Z: f32 = ${fp.maxZ.toFixed(5)};

/// Walk AABBs split across \`generated_walk_surfaces/part_*.rs\` for reviewability.
pub static WALK_SURFACE_AABB_SHARDS: &[&[([f32; 3], [f32; 3])]] = &[
${shardRefs}
];
`;

writeFileSync(join(root, "apps/server/src/generated_walk_surfaces.rs"), mainRs, "utf8");
console.log(
  `Wrote ${aabbs.length} walk AABBs across ${shardCount} shards under apps/server/src/generated_walk_surfaces/`,
);
