import { describe, expect, it } from "vitest";
import {
  WORLD_SOUND_KIND_CONSUME_DRINK,
  WORLD_SOUND_KIND_CONSUME_EAT,
  WORLD_SOUND_KIND_CONSUME_SMOKE,
  WORLD_SOUND_KIND_ELEVATOR_CAB_ARRIVAL,
  WORLD_SOUND_KIND_ELEVATOR_FLOOR_BUTTON,
  WORLD_SOUND_KIND_ELEVATOR_LANDING_HAIL,
  WORLD_SOUND_KIND_LANDING_EXTERIOR_DOOR_CLOSE,
  WORLD_SOUND_KIND_LANDING_EXTERIOR_DOOR_OPEN,
  WORLD_SOUND_KIND_FOOTSTEP,
  WORLD_SOUND_KIND_ITEM_PICKUP,
  WORLD_SOUND_KIND_MELEE_FLESH_HIT,
  WORLD_SOUND_KIND_MELEE_WEAPON_SWING,
} from "./audio/worldProximityAudio.js";

/** Numeric `kind` must match `apps/server/src/world_sound.rs` `KIND_*`. */
describe("world sound kinds", () => {
  it("matches server KIND_* constants", () => {
    expect(WORLD_SOUND_KIND_FOOTSTEP).toBe(0);
    expect(WORLD_SOUND_KIND_MELEE_WEAPON_SWING).toBe(1);
    expect(WORLD_SOUND_KIND_ITEM_PICKUP).toBe(2);
    expect(WORLD_SOUND_KIND_CONSUME_EAT).toBe(3);
    expect(WORLD_SOUND_KIND_CONSUME_DRINK).toBe(4);
    expect(WORLD_SOUND_KIND_ELEVATOR_FLOOR_BUTTON).toBe(5);
    expect(WORLD_SOUND_KIND_ELEVATOR_LANDING_HAIL).toBe(6);
    expect(WORLD_SOUND_KIND_LANDING_EXTERIOR_DOOR_OPEN).toBe(7);
    expect(WORLD_SOUND_KIND_LANDING_EXTERIOR_DOOR_CLOSE).toBe(8);
    expect(WORLD_SOUND_KIND_ELEVATOR_CAB_ARRIVAL).toBe(9);
    expect(WORLD_SOUND_KIND_MELEE_FLESH_HIT).toBe(10);
    expect(WORLD_SOUND_KIND_CONSUME_SMOKE).toBe(13);
  });
});
