import type { EditorState } from "../state/editorStore.js";

export function selectEditorChromeStore(s: EditorState) {
  return {
    mode: s.mode,
    building: s.building,
    floorDocs: s.floorDocs,
    interiorDocs: s.interiorDocs,
    activeFloorDocId: s.activeFloorDocId,
    activeInteriorDocId: s.activeInteriorDocId,
    focusedStoryLevelIndex: s.focusedStoryLevelIndex,
    selectedId: s.selectedId,
    dirty: s.dirty,
    transformMode: s.transformMode,
    gridSnapM: s.gridSnapM,
    shadowsEnabled: s.shadowsEnabled,
    useHdriEnvironment: s.useHdriEnvironment,
    historyPast: s.historyPast,
    historyFuture: s.historyFuture,
    setMode: s.setMode,
    setActiveFloorDocId: s.setActiveFloorDocId,
    setActiveInteriorDocId: s.setActiveInteriorDocId,
    setFocusedStoryLevelIndex: s.setFocusedStoryLevelIndex,
    setTransformMode: s.setTransformMode,
    setGridSnapM: s.setGridSnapM,
    setShadowsEnabled: s.setShadowsEnabled,
    setUseHdriEnvironment: s.setUseHdriEnvironment,
    undo: s.undo,
    redo: s.redo,
    updatePlacedObject: s.updatePlacedObject,
    updateInteriorPlacement: s.updateInteriorPlacement,
    addFloorObject: s.addFloorObject,
    deleteFloorObject: s.deleteFloorObject,
    duplicateFloorObject: s.duplicateFloorObject,
    addInteriorPlacement: s.addInteriorPlacement,
    deleteInteriorPlacement: s.deleteInteriorPlacement,
    duplicateInteriorPlacement: s.duplicateInteriorPlacement,
    patchBuilding: s.patchBuilding,
    setSelectedId: s.setSelectedId,
  };
}
