// AUTO-GENERATED by scripts/gen-walk-aabbs.ts — collision solids shard 20/20 — do not hand-edit.
static PART_0019: &[([f32; 3], [f32; 3])] = &[
    ([-13.84500, 61.00000, 76.47964], [-13.42500, 61.12000, 77.88483]),
    ([-13.84500, 61.00000, 77.94483], [-13.42500, 61.12000, 79.32000]),
];
